<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-IO: /mnt/c/Users/abell/Documents/GitHub/NRE-IO/src/IO/FileStream/BinaryInput/Stream/NRE_BinaryInputStream.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_fae119eb913a40fe8ed97cde8b98911e.php">IO</a></li><li class="navelem"><a class="el" href="dir_0ca3aa3018c3eba24bd0177e1bd7d738.php">FileStream</a></li><li class="navelem"><a class="el" href="dir_69f5a99671e0b76b37f21d1b0cdae228.php">BinaryInput</a></li><li class="navelem"><a class="el" href="dir_4e16841adf17f189d6e259d050c38fac.php">Stream</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_BinaryInputStream.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___binary_input_stream_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">     #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;fstream&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_i_o.php">IO</a> {</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;</div><div class="line"><a name="l00029"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">   29</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">BinaryInputStream</a> {</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;                <span class="keyword">public</span>:    <span class="comment">// Methods</span></div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#a63da2d140ad77e663a65076df5cdb944">BinaryInputStream</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;                    <span class="comment">//## Copy-Constructor ##//</span></div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#a63da2d140ad77e663a65076df5cdb944">BinaryInputStream</a>(<a class="code" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">BinaryInputStream</a> <span class="keyword">const</span>&amp; i) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;                    <span class="comment">//## Move-Constructor ##//</span></div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#a63da2d140ad77e663a65076df5cdb944">BinaryInputStream</a>(<a class="code" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">BinaryInputStream</a> &amp;&amp; i) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;<span class="comment"></span>                        <span class="keyword">virtual</span> <a class="code" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#ac39b3d01a85995cebacdfa64a1a1b588">~BinaryInputStream</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;<span class="comment"></span>                        <span class="keyword">virtual</span> std::fstream&amp; <a class="code" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#a746061ba00a5188ddf5d55143c7aed4b">getStream</a>() = 0;</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;</div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;<span class="comment"></span>                        <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00070"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#acec53ec7e9fa9adb1b7ad8b50f7364c8">   70</a></span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#acec53ec7e9fa9adb1b7ad8b50f7364c8">readBinary</a>(T&amp; <span class="keywordtype">object</span>, <span class="keywordtype">size_t</span> sizeInBytes) {</div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;                            <a class="code" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#a746061ba00a5188ddf5d55143c7aed4b">getStream</a>().read(reinterpret_cast&lt;char *&gt;(&amp;<span class="keywordtype">object</span>), sizeInBytes);</div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;                        }</div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;</div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">BinaryInputStream</a>&amp; <a class="code" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#aa72a8c1f1905ca197325afbcba4cd7ed">operator =</a>(<a class="code" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">BinaryInputStream</a> <span class="keyword">const</span>&amp; i) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;                        <a class="code" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">BinaryInputStream</a>&amp; <a class="code" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#aa72a8c1f1905ca197325afbcba4cd7ed">operator =</a>(<a class="code" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">BinaryInputStream</a> &amp;&amp; i) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;            };</div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;        }</div><div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;    }</div><div class="ttc" id="class_n_r_e_1_1_i_o_1_1_binary_input_stream_php_a746061ba00a5188ddf5d55143c7aed4b"><div class="ttname"><a href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#a746061ba00a5188ddf5d55143c7aed4b">NRE::IO::BinaryInputStream::getStream</a></div><div class="ttdeci">virtual std::fstream &amp; getStream()=0</div></div>
<div class="ttc" id="namespace_i_o_php"><div class="ttname"><a href="namespace_i_o.php">IO</a></div><div class="ttdoc">IO&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_i_o_1_1_binary_input_stream_php_aa72a8c1f1905ca197325afbcba4cd7ed"><div class="ttname"><a href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#aa72a8c1f1905ca197325afbcba4cd7ed">NRE::IO::BinaryInputStream::operator=</a></div><div class="ttdeci">BinaryInputStream &amp; operator=(BinaryInputStream const &amp;i)=delete</div></div>
<div class="ttc" id="class_n_r_e_1_1_i_o_1_1_binary_input_stream_php_a63da2d140ad77e663a65076df5cdb944"><div class="ttname"><a href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#a63da2d140ad77e663a65076df5cdb944">NRE::IO::BinaryInputStream::BinaryInputStream</a></div><div class="ttdeci">BinaryInputStream()=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_i_o_1_1_binary_input_stream_php"><div class="ttname"><a href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">NRE::IO::BinaryInputStream</a></div><div class="ttdoc">Base interface for binary input related stream. </div><div class="ttdef"><b>Definition:</b> NRE_BinaryInputStream.hpp:29</div></div>
<div class="ttc" id="class_n_r_e_1_1_i_o_1_1_binary_input_stream_php_acec53ec7e9fa9adb1b7ad8b50f7364c8"><div class="ttname"><a href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#acec53ec7e9fa9adb1b7ad8b50f7364c8">NRE::IO::BinaryInputStream::readBinary</a></div><div class="ttdeci">void readBinary(T &amp;object, size_t sizeInBytes)</div><div class="ttdef"><b>Definition:</b> NRE_BinaryInputStream.hpp:70</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_i_o_1_1_binary_input_stream_php_ac39b3d01a85995cebacdfa64a1a1b588"><div class="ttname"><a href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#ac39b3d01a85995cebacdfa64a1a1b588">NRE::IO::BinaryInputStream::~BinaryInputStream</a></div><div class="ttdeci">virtual ~BinaryInputStream()=default</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
