<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-IO: /mnt/c/Users/abell/Documents/GitHub/NRE-IO/src/IO/FileStream/Output/Stream/NRE_OutputStream.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_fae119eb913a40fe8ed97cde8b98911e.php">IO</a></li><li class="navelem"><a class="el" href="dir_0ca3aa3018c3eba24bd0177e1bd7d738.php">FileStream</a></li><li class="navelem"><a class="el" href="dir_e5f6d8b1531c0dcd5388e93cbfd72a55.php">Output</a></li><li class="navelem"><a class="el" href="dir_05a885a8e57ea792255b94a13f14e89d.php">Stream</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_OutputStream.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___output_stream_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">     #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;fstream&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;</div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="preprocessor">    #include &lt;Header/NRE_Utility.hpp&gt;</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;</div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_i_o.php">IO</a> {</div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;</div><div class="line"><a name="l00031"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">   31</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a> {</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;                <span class="keyword">public</span>:    <span class="comment">// Methods</span></div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a1efcdc994b4d8d955460a813d525bf9d">OutputStream</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;</div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;                    <span class="comment">//## Copy-Constructor ##//</span></div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a1efcdc994b4d8d955460a813d525bf9d">OutputStream</a>(<a class="code" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a> <span class="keyword">const</span>&amp; o) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;                    <span class="comment">//## Move-Constructor ##//</span></div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a1efcdc994b4d8d955460a813d525bf9d">OutputStream</a>(<a class="code" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a> &amp;&amp; o) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;<span class="comment"></span>                        <span class="keyword">virtual</span> <a class="code" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#ab93399476f8933a7062c9ab3c0db0e05">~OutputStream</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;<span class="comment"></span>                        <span class="keyword">virtual</span> std::fstream&amp; <a class="code" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#aa67ea34d4faa3bbd24d9df13979be205">getStream</a>() = 0;</div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;                        std::streampos <a class="code" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a4865057a0271a36ec3cde6e76282ebfc">getPosition</a>();</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;</div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;<span class="comment"></span>                        <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00075"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a2347d2de8cf213aee37148c25c5bdf6c">   75</a></span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a2347d2de8cf213aee37148c25c5bdf6c">write</a>(T <span class="keyword">const</span>&amp; <span class="keywordtype">object</span>) {</div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;                            <a class="code" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#aa67ea34d4faa3bbd24d9df13979be205">getStream</a>() &lt;&lt; object;</div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;                        }</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#ab17afff8528ac5d7ba2fd8a5577022e2">seekBegin</a>(<span class="keywordtype">size_t</span> offset = 0);</div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a78c55f5724508b1cd92aea071306029d">seekEnd</a>(<span class="keywordtype">size_t</span> offset = 0);</div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;</div><div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a>&amp; <a class="code" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a19aca25943b90833a09c633f2ad4a097">operator =</a>(<a class="code" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a> <span class="keyword">const</span>&amp; o) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;                        <a class="code" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a>&amp; <a class="code" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a19aca25943b90833a09c633f2ad4a097">operator =</a>(<a class="code" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a> &amp;&amp; o) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;            };</div><div class="line"><a name="l00103"></a><span class="lineno">  103</span>&#160;        }</div><div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;    }</div><div class="line"><a name="l00105"></a><span class="lineno">  105</span>&#160;</div><div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;<span class="preprocessor">    #include &quot;NRE_OutputStream.tpp&quot;</span></div><div class="ttc" id="class_n_r_e_1_1_i_o_1_1_output_stream_php_a78c55f5724508b1cd92aea071306029d"><div class="ttname"><a href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a78c55f5724508b1cd92aea071306029d">NRE::IO::OutputStream::seekEnd</a></div><div class="ttdeci">void seekEnd(size_t offset=0)</div></div>
<div class="ttc" id="class_n_r_e_1_1_i_o_1_1_output_stream_php_a2347d2de8cf213aee37148c25c5bdf6c"><div class="ttname"><a href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a2347d2de8cf213aee37148c25c5bdf6c">NRE::IO::OutputStream::write</a></div><div class="ttdeci">void write(T const &amp;object)</div><div class="ttdef"><b>Definition:</b> NRE_OutputStream.hpp:75</div></div>
<div class="ttc" id="namespace_i_o_php"><div class="ttname"><a href="namespace_i_o.php">IO</a></div><div class="ttdoc">IO&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_i_o_1_1_output_stream_php_a19aca25943b90833a09c633f2ad4a097"><div class="ttname"><a href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a19aca25943b90833a09c633f2ad4a097">NRE::IO::OutputStream::operator=</a></div><div class="ttdeci">OutputStream &amp; operator=(OutputStream const &amp;o)=delete</div></div>
<div class="ttc" id="class_n_r_e_1_1_i_o_1_1_output_stream_php_aa67ea34d4faa3bbd24d9df13979be205"><div class="ttname"><a href="class_n_r_e_1_1_i_o_1_1_output_stream.php#aa67ea34d4faa3bbd24d9df13979be205">NRE::IO::OutputStream::getStream</a></div><div class="ttdeci">virtual std::fstream &amp; getStream()=0</div></div>
<div class="ttc" id="class_n_r_e_1_1_i_o_1_1_output_stream_php_a1efcdc994b4d8d955460a813d525bf9d"><div class="ttname"><a href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a1efcdc994b4d8d955460a813d525bf9d">NRE::IO::OutputStream::OutputStream</a></div><div class="ttdeci">OutputStream()=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_i_o_1_1_output_stream_php"><div class="ttname"><a href="class_n_r_e_1_1_i_o_1_1_output_stream.php">NRE::IO::OutputStream</a></div><div class="ttdoc">Base interface for output related stream. </div><div class="ttdef"><b>Definition:</b> NRE_OutputStream.hpp:31</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_i_o_1_1_output_stream_php_ab93399476f8933a7062c9ab3c0db0e05"><div class="ttname"><a href="class_n_r_e_1_1_i_o_1_1_output_stream.php#ab93399476f8933a7062c9ab3c0db0e05">NRE::IO::OutputStream::~OutputStream</a></div><div class="ttdeci">virtual ~OutputStream()=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_i_o_1_1_output_stream_php_a4865057a0271a36ec3cde6e76282ebfc"><div class="ttname"><a href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a4865057a0271a36ec3cde6e76282ebfc">NRE::IO::OutputStream::getPosition</a></div><div class="ttdeci">std::streampos getPosition()</div></div>
<div class="ttc" id="class_n_r_e_1_1_i_o_1_1_output_stream_php_ab17afff8528ac5d7ba2fd8a5577022e2"><div class="ttname"><a href="class_n_r_e_1_1_i_o_1_1_output_stream.php#ab17afff8528ac5d7ba2fd8a5577022e2">NRE::IO::OutputStream::seekBegin</a></div><div class="ttdeci">void seekBegin(size_t offset=0)</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
