<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-IO: /mnt/c/Users/abell/Documents/GitHub/NRE-IO/src/Exception/NRE_FileNotOpeningException.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_8325968175170435003107496b1cfdde.php">Exception</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_FileNotOpeningException.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___file_not_opening_exception_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &quot;<a class="code" href="_n_r_e___i_o_exception_8hpp.php">NRE_IOException.hpp</a>&quot;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_exception.php">Exception</a> {</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;</div><div class="line"><a name="l00029"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_exception_1_1_file_not_opening_exception.php">   29</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_exception_1_1_file_not_opening_exception.php">FileNotOpeningException</a> : <span class="keyword">public</span> <a class="code" href="class_n_r_e_1_1_exception_1_1_i_o_exception.php">IOException</a> {</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;                <span class="keyword">public</span>:</div><div class="line"><a name="l00035"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_exception_1_1_file_not_opening_exception.php#ae5762928257e5523f159f98f10aad64f">   35</a></span>&#160;                    <a class="code" href="class_n_r_e_1_1_exception_1_1_file_not_opening_exception.php#ae5762928257e5523f159f98f10aad64f">FileNotOpeningException</a>(Utility::String <span class="keyword">const</span>&amp; log) <span class="keywordflow">throw</span>() : <a class="code" href="class_n_r_e_1_1_exception_1_1_i_o_exception.php#a855a98a399ad4bbc1f1be2ad2da1cf24">IOException</a>(<span class="stringliteral">&quot;FileNotOpening Exception : &quot;</span> + log) {</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;                    }</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;            };</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;        }</div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;    }</div><div class="ttc" id="class_n_r_e_1_1_exception_1_1_file_not_opening_exception_php_ae5762928257e5523f159f98f10aad64f"><div class="ttname"><a href="class_n_r_e_1_1_exception_1_1_file_not_opening_exception.php#ae5762928257e5523f159f98f10aad64f">NRE::Exception::FileNotOpeningException::FileNotOpeningException</a></div><div class="ttdeci">FileNotOpeningException(Utility::String const &amp;log)</div><div class="ttdef"><b>Definition:</b> NRE_FileNotOpeningException.hpp:35</div></div>
<div class="ttc" id="namespace_exception_php"><div class="ttname"><a href="namespace_exception.php">Exception</a></div><div class="ttdoc">Utility&amp;#39;s API. </div></div>
<div class="ttc" id="_n_r_e___i_o_exception_8hpp_php"><div class="ttname"><a href="_n_r_e___i_o_exception_8hpp.php">NRE_IOException.hpp</a></div><div class="ttdoc">Declaration of System&amp;#39;s API&amp;#39;s Object : IOException. </div></div>
<div class="ttc" id="class_n_r_e_1_1_exception_1_1_i_o_exception_php"><div class="ttname"><a href="class_n_r_e_1_1_exception_1_1_i_o_exception.php">NRE::Exception::IOException</a></div><div class="ttdoc">An exception thrown by io operation. </div><div class="ttdef"><b>Definition:</b> NRE_IOException.hpp:29</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_exception_1_1_file_not_opening_exception_php"><div class="ttname"><a href="class_n_r_e_1_1_exception_1_1_file_not_opening_exception.php">NRE::Exception::FileNotOpeningException</a></div><div class="ttdoc">An exception thrown when attempting to open a file. </div><div class="ttdef"><b>Definition:</b> NRE_FileNotOpeningException.hpp:29</div></div>
<div class="ttc" id="class_n_r_e_1_1_exception_1_1_i_o_exception_php_a855a98a399ad4bbc1f1be2ad2da1cf24"><div class="ttname"><a href="class_n_r_e_1_1_exception_1_1_i_o_exception.php#a855a98a399ad4bbc1f1be2ad2da1cf24">NRE::Exception::IOException::IOException</a></div><div class="ttdeci">IOException(Utility::String const &amp;log)</div><div class="ttdef"><b>Definition:</b> NRE_IOException.hpp:35</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
