<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-IO: NRE::IO::OutputStream Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>IO</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_i_o_1_1_output_stream-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::IO::OutputStream Class Reference<span class="mlabels"><span class="mlabel">abstract</span></span></div>  </div>
</div><!--header-->
<div class="contents">

<p>Base interface for output related stream.  
 <a href="class_n_r_e_1_1_i_o_1_1_output_stream.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___output_stream_8hpp_source.php">NRE_OutputStream.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::IO::OutputStream:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_i_o_1_1_output_stream.png" usemap="#NRE::IO::OutputStream_map" alt=""/>
  <map id="NRE::IO::OutputStream_map" name="NRE::IO::OutputStream_map">
<area href="class_n_r_e_1_1_i_o_1_1_i_o_file.php" title="Manage Input-Output file stream. " alt="NRE::IO::IOFile" shape="rect" coords="0,56,157,80"/>
<area href="class_n_r_e_1_1_i_o_1_1_output_file.php" title="Manage output file stream. " alt="NRE::IO::OutputFile" shape="rect" coords="167,56,324,80"/>
<area href="class_n_r_e_1_1_i_o_1_1_binary_i_o_file.php" title="Manage Binary Input-Output file stream. " alt="NRE::IO::BinaryIOFile" shape="rect" coords="0,112,157,136"/>
<area href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php" title="Manage binary output file stream. " alt="NRE::IO::BinaryOutputFile" shape="rect" coords="167,112,324,136"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a1efcdc994b4d8d955460a813d525bf9d"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a1efcdc994b4d8d955460a813d525bf9d">OutputStream</a> ()=default</td></tr>
<tr class="separator:a1efcdc994b4d8d955460a813d525bf9d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a58f80840a0b7cd9d76a732c0df1fce60"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a58f80840a0b7cd9d76a732c0df1fce60">OutputStream</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a> const &amp;o)=delete</td></tr>
<tr class="separator:a58f80840a0b7cd9d76a732c0df1fce60"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7113e072849339312d22fb688dd18476"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a7113e072849339312d22fb688dd18476">OutputStream</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a> &amp;&amp;o)=default</td></tr>
<tr class="separator:a7113e072849339312d22fb688dd18476"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab93399476f8933a7062c9ab3c0db0e05"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#ab93399476f8933a7062c9ab3c0db0e05">~OutputStream</a> ()=default</td></tr>
<tr class="separator:ab93399476f8933a7062c9ab3c0db0e05"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa67ea34d4faa3bbd24d9df13979be205"><td class="memItemLeft" align="right" valign="top">virtual std::fstream &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#aa67ea34d4faa3bbd24d9df13979be205">getStream</a> ()=0</td></tr>
<tr class="separator:aa67ea34d4faa3bbd24d9df13979be205"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4865057a0271a36ec3cde6e76282ebfc"><td class="memItemLeft" align="right" valign="top">std::streampos&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a4865057a0271a36ec3cde6e76282ebfc">getPosition</a> ()</td></tr>
<tr class="separator:a4865057a0271a36ec3cde6e76282ebfc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2347d2de8cf213aee37148c25c5bdf6c"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:a2347d2de8cf213aee37148c25c5bdf6c"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a2347d2de8cf213aee37148c25c5bdf6c">write</a> (T const &amp;object)</td></tr>
<tr class="separator:a2347d2de8cf213aee37148c25c5bdf6c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab17afff8528ac5d7ba2fd8a5577022e2"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#ab17afff8528ac5d7ba2fd8a5577022e2">seekBegin</a> (size_t offset=0)</td></tr>
<tr class="separator:ab17afff8528ac5d7ba2fd8a5577022e2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a78c55f5724508b1cd92aea071306029d"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a78c55f5724508b1cd92aea071306029d">seekEnd</a> (size_t offset=0)</td></tr>
<tr class="separator:a78c55f5724508b1cd92aea071306029d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a19aca25943b90833a09c633f2ad4a097"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a19aca25943b90833a09c633f2ad4a097">operator=</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a> const &amp;o)=delete</td></tr>
<tr class="separator:a19aca25943b90833a09c633f2ad4a097"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adedec60a6e3842e33bbd650981339d16"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#adedec60a6e3842e33bbd650981339d16">operator=</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a> &amp;&amp;o)=default</td></tr>
<tr class="separator:adedec60a6e3842e33bbd650981339d16"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Base interface for output related stream. </p>
<p><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php" title="Base interface for output related stream. ">OutputStream</a> </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a1efcdc994b4d8d955460a813d525bf9d"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::IO::OutputStream::OutputStream </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Default constructor </p>

</div>
</div>
<a class="anchor" id="a58f80840a0b7cd9d76a732c0df1fce60"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::IO::OutputStream::OutputStream </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a> const &amp;&#160;</td>
          <td class="paramname"><em>o</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">o</td><td>the output stream to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a7113e072849339312d22fb688dd18476"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::IO::OutputStream::OutputStream </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>o</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move o into this, leaving o empty </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">o</td><td>the output stream to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ab93399476f8933a7062c9ab3c0db0e05"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual NRE::IO::OutputStream::~OutputStream </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">virtual</span><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php" title="Base interface for output related stream. ">OutputStream</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a4865057a0271a36ec3cde6e76282ebfc"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::streampos NRE::IO::OutputStream::getPosition </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the stream cursor position </dd></dl>

</div>
</div>
<a class="anchor" id="aa67ea34d4faa3bbd24d9df13979be205"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual std::fstream&amp; NRE::IO::OutputStream::getStream </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">pure virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the file's stream </dd></dl>

<p>Implemented in <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_i_o_file.php#ae312212af94dc55296cbeec60806b2bc">NRE::IO::BinaryIOFile</a>, <a class="el" href="class_n_r_e_1_1_i_o_1_1_i_o_file.php#a0f6ed5ca0893d4444e439ac07e391e67">NRE::IO::IOFile</a>, <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php#a226f850a5fc4d714d97c5688e94c1d7e">NRE::IO::BinaryOutputFile</a>, and <a class="el" href="class_n_r_e_1_1_i_o_1_1_output_file.php#a009140e861b7b27f2a1569a833081303">NRE::IO::OutputFile</a>.</p>

</div>
</div>
<a class="anchor" id="a19aca25943b90833a09c633f2ad4a097"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a>&amp; NRE::IO::OutputStream::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a> const &amp;&#160;</td>
          <td class="paramname"><em>o</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy assignment forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">o</td><td>the output stream to copy </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="adedec60a6e3842e33bbd650981339d16"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a>&amp; NRE::IO::OutputStream::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>o</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move assignment of o into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">o</td><td>the output stream to move </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="ab17afff8528ac5d7ba2fd8a5577022e2"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::IO::OutputStream::seekBegin </td>
          <td>(</td>
          <td class="paramtype">size_t&#160;</td>
          <td class="paramname"><em>offset</em> = <code>0</code></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set the file cursor position to the begin + offset </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">offset</td><td>the file's offset </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a78c55f5724508b1cd92aea071306029d"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::IO::OutputStream::seekEnd </td>
          <td>(</td>
          <td class="paramtype">size_t&#160;</td>
          <td class="paramname"><em>offset</em> = <code>0</code></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set the file cursor position to the end - offset </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">offset</td><td>the file's offset </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a2347d2de8cf213aee37148c25c5bdf6c"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::IO::OutputStream::write </td>
          <td>(</td>
          <td class="paramtype">T const &amp;&#160;</td>
          <td class="paramname"><em>object</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Write the passed data into the file stream </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">object</td><td>the data to write </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-IO/src/IO/FileStream/Output/Stream/<a class="el" href="_n_r_e___output_stream_8hpp_source.php">NRE_OutputStream.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
