<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-IO: NRE::IO::InputStream Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>IO</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">InputStream</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_i_o_1_1_input_stream-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::IO::InputStream Class Reference<span class="mlabels"><span class="mlabel">abstract</span></span></div>  </div>
</div><!--header-->
<div class="contents">

<p>Base interface for input related stream.  
 <a href="class_n_r_e_1_1_i_o_1_1_input_stream.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___input_stream_8hpp_source.php">NRE_InputStream.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::IO::InputStream:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_i_o_1_1_input_stream.png" usemap="#NRE::IO::InputStream_map" alt=""/>
  <map id="NRE::IO::InputStream_map" name="NRE::IO::InputStream_map">
<area href="class_n_r_e_1_1_i_o_1_1_input_file.php" title="Manage input file stream. " alt="NRE::IO::InputFile" shape="rect" coords="0,56,147,80"/>
<area href="class_n_r_e_1_1_i_o_1_1_i_o_file.php" title="Manage Input-Output file stream. " alt="NRE::IO::IOFile" shape="rect" coords="157,56,304,80"/>
<area href="class_n_r_e_1_1_i_o_1_1_binary_input_file.php" title="Manage binary input file stream. " alt="NRE::IO::BinaryInputFile" shape="rect" coords="0,112,147,136"/>
<area href="class_n_r_e_1_1_i_o_1_1_binary_i_o_file.php" title="Manage Binary Input-Output file stream. " alt="NRE::IO::BinaryIOFile" shape="rect" coords="157,112,304,136"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:ae77d706d7e3c1a59353d88b0e1ff9476"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#ae77d706d7e3c1a59353d88b0e1ff9476">InputStream</a> ()=default</td></tr>
<tr class="separator:ae77d706d7e3c1a59353d88b0e1ff9476"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8d29d8774ad30cf1c1ebf631e8e429c9"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#a8d29d8774ad30cf1c1ebf631e8e429c9">InputStream</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">InputStream</a> const &amp;i)=delete</td></tr>
<tr class="separator:a8d29d8774ad30cf1c1ebf631e8e429c9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afbd283899fe6ea4e62c94d44cf28af5e"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#afbd283899fe6ea4e62c94d44cf28af5e">InputStream</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">InputStream</a> &amp;&amp;i)=default</td></tr>
<tr class="separator:afbd283899fe6ea4e62c94d44cf28af5e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6640a5cd0ec7f081452aea53bde44f34"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#a6640a5cd0ec7f081452aea53bde44f34">~InputStream</a> ()=default</td></tr>
<tr class="separator:a6640a5cd0ec7f081452aea53bde44f34"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4e61262f16391d9a592093cc13ed85d8"><td class="memItemLeft" align="right" valign="top">virtual std::fstream &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#a4e61262f16391d9a592093cc13ed85d8">getStream</a> ()=0</td></tr>
<tr class="separator:a4e61262f16391d9a592093cc13ed85d8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abbf6f1014d1be839a1841c51bad87b3c"><td class="memItemLeft" align="right" valign="top">std::streampos&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#abbf6f1014d1be839a1841c51bad87b3c">getPosition</a> ()</td></tr>
<tr class="separator:abbf6f1014d1be839a1841c51bad87b3c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4863ac832c227dc838e4d8a74db97c6a"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:a4863ac832c227dc838e4d8a74db97c6a"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#a4863ac832c227dc838e4d8a74db97c6a">read</a> (T &amp;object)</td></tr>
<tr class="separator:a4863ac832c227dc838e4d8a74db97c6a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af91eeb1fc3eb2a8ea3c623d0d140e6a4"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#af91eeb1fc3eb2a8ea3c623d0d140e6a4">readLine</a> (Utility::String &amp;line)</td></tr>
<tr class="separator:af91eeb1fc3eb2a8ea3c623d0d140e6a4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7365375159cb13f7d4d1004e39a622c3"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#a7365375159cb13f7d4d1004e39a622c3">seekBegin</a> (size_t offset=0)</td></tr>
<tr class="separator:a7365375159cb13f7d4d1004e39a622c3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae0fbdbcce3b727547ad94f035608906d"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#ae0fbdbcce3b727547ad94f035608906d">seekEnd</a> (size_t offset=0)</td></tr>
<tr class="separator:ae0fbdbcce3b727547ad94f035608906d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5e95195616de0936b5c54377b7685e6c"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">InputStream</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#a5e95195616de0936b5c54377b7685e6c">operator=</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">InputStream</a> const &amp;i)=delete</td></tr>
<tr class="separator:a5e95195616de0936b5c54377b7685e6c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae268a182a6e21b17ccb8f6e2af98d2b2"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">InputStream</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#ae268a182a6e21b17ccb8f6e2af98d2b2">operator=</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">InputStream</a> &amp;&amp;i)=default</td></tr>
<tr class="separator:ae268a182a6e21b17ccb8f6e2af98d2b2"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Base interface for input related stream. </p>
<p><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php" title="Base interface for input related stream. ">InputStream</a> </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="ae77d706d7e3c1a59353d88b0e1ff9476"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::IO::InputStream::InputStream </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Default constructor </p>

</div>
</div>
<a class="anchor" id="a8d29d8774ad30cf1c1ebf631e8e429c9"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::IO::InputStream::InputStream </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">InputStream</a> const &amp;&#160;</td>
          <td class="paramname"><em>i</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the input stream to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="afbd283899fe6ea4e62c94d44cf28af5e"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::IO::InputStream::InputStream </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">InputStream</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>i</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move i into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the input stream to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a6640a5cd0ec7f081452aea53bde44f34"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual NRE::IO::InputStream::~InputStream </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">virtual</span><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php" title="Base interface for input related stream. ">InputStream</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="abbf6f1014d1be839a1841c51bad87b3c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::streampos NRE::IO::InputStream::getPosition </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the stream cursor position </dd></dl>

</div>
</div>
<a class="anchor" id="a4e61262f16391d9a592093cc13ed85d8"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual std::fstream&amp; NRE::IO::InputStream::getStream </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">pure virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the file's stream </dd></dl>

<p>Implemented in <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_i_o_file.php#ae312212af94dc55296cbeec60806b2bc">NRE::IO::BinaryIOFile</a>, <a class="el" href="class_n_r_e_1_1_i_o_1_1_i_o_file.php#a0f6ed5ca0893d4444e439ac07e391e67">NRE::IO::IOFile</a>, <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_file.php#abd74b00ec06cb5c1c828a68024af2f2a">NRE::IO::BinaryInputFile</a>, and <a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php#a8a06ca02590f62804bcaa2fd08c54538">NRE::IO::InputFile</a>.</p>

</div>
</div>
<a class="anchor" id="a5e95195616de0936b5c54377b7685e6c"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">InputStream</a>&amp; NRE::IO::InputStream::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">InputStream</a> const &amp;&#160;</td>
          <td class="paramname"><em>i</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy assignment forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the input stream to copy </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="ae268a182a6e21b17ccb8f6e2af98d2b2"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">InputStream</a>&amp; NRE::IO::InputStream::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">InputStream</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>i</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move assignment of i into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the input stream to move </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a4863ac832c227dc838e4d8a74db97c6a"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::IO::InputStream::read </td>
          <td>(</td>
          <td class="paramtype">T &amp;&#160;</td>
          <td class="paramname"><em>object</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Read into the passed data from the file stream </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">object</td><td>the data to store the read return </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="af91eeb1fc3eb2a8ea3c623d0d140e6a4"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::IO::InputStream::readLine </td>
          <td>(</td>
          <td class="paramtype">Utility::String &amp;&#160;</td>
          <td class="paramname"><em>line</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Read a file's line and store it into the given string </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">line</td><td>the string to store the read line </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a7365375159cb13f7d4d1004e39a622c3"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::IO::InputStream::seekBegin </td>
          <td>(</td>
          <td class="paramtype">size_t&#160;</td>
          <td class="paramname"><em>offset</em> = <code>0</code></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set the file cursor position to the begin + offset </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">offset</td><td>the file's offset </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ae0fbdbcce3b727547ad94f035608906d"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::IO::InputStream::seekEnd </td>
          <td>(</td>
          <td class="paramtype">size_t&#160;</td>
          <td class="paramname"><em>offset</em> = <code>0</code></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set the file cursor position to the end - offset </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">offset</td><td>the file's offset </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-IO/src/IO/FileStream/Input/Stream/<a class="el" href="_n_r_e___input_stream_8hpp_source.php">NRE_InputStream.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
