<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-IO: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>IO</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php">InputFile</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE::IO::InputFile Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php">NRE::IO::InputFile</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#ae955f8bc07d667649e7f045c2bbbef49">exist</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">NRE::IO::File</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#ae31e8c433fdbda9a37130168b5fb2858">File</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">NRE::IO::File</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a71392564fdd4bdcbad2a9dec89a0aee1">File</a>(Utility::String const &amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">NRE::IO::File</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#af49f63c9e981ee77ebe0d71caa65cfad">File</a>(char const p[])</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">NRE::IO::File</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#ada63f8f00e27c1d6ec5ea6f09b5f9c75">File</a>(File const &amp;f)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">NRE::IO::File</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a9860259838f1a163a7a931b3cbae3174">File</a>(File &amp;&amp;f)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">NRE::IO::File</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#a7bef175fe08cc377c872103f61864859">FileStream</a>()=delete</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php">NRE::IO::FileStream</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#a984be898303f6344d5c15efb5fa4e886">FileStream</a>(File const &amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php">NRE::IO::FileStream</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#afc239902cef34ecfd890cf69a5172c6d">FileStream</a>(FileStream const &amp;f)=delete</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php">NRE::IO::FileStream</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#ae9637c1e640b0dacecad04bf957a91f0">FileStream</a>(FileStream &amp;&amp;f)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php">NRE::IO::FileStream</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php#a4c8886a207655e70e21f23f1a694e3dd">getMode</a>() const override</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php">NRE::IO::InputFile</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a6ff1d432623961e08ed64eeb97d547c7">getPath</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">NRE::IO::File</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#abbf6f1014d1be839a1841c51bad87b3c">getPosition</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">NRE::IO::InputStream</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php#a8a06ca02590f62804bcaa2fd08c54538">getStream</a>() override</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php">NRE::IO::InputFile</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php#a692608a4559e9eb9ff281e5b88ef6cab">InputFile</a>()=delete</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php">NRE::IO::InputFile</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php#aa4441dc2b489831c4b70bec2ac6d410a">InputFile</a>(File const &amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php">NRE::IO::InputFile</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php#a3964a2eeaecfdcb0df53c6960106ee79">InputFile</a>(InputFile &amp;&amp;i)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php">NRE::IO::InputFile</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#ae77d706d7e3c1a59353d88b0e1ff9476">InputStream</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">NRE::IO::InputStream</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#a8d29d8774ad30cf1c1ebf631e8e429c9">InputStream</a>(InputStream const &amp;i)=delete</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">NRE::IO::InputStream</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#afbd283899fe6ea4e62c94d44cf28af5e">InputStream</a>(InputStream &amp;&amp;i)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">NRE::IO::InputStream</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#a6cb9f46d893839b4518cc86b3afe2178">isOpen</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php">NRE::IO::FileStream</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#a24979d0affac7992e181820b881941eb">open</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php">NRE::IO::FileStream</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#af0677c0d90634a88472f629567ca5238">openEmpty</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php">NRE::IO::FileStream</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#af5e129d3ca95bbc6db8c43ad84aaaf6c">operator+</a>(Utility::String const &amp;s) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">NRE::IO::File</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a2009e071a45be3a88bcfc03bd7868b50">operator+</a>(File const &amp;f) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">NRE::IO::File</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php#a0e874eb62d5ee7e5e2ef1787422c81b6">operator=</a>(InputFile &amp;&amp;i)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php">NRE::IO::InputFile</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#a357c757b87bc7876f0b1f2fb7f96edb1">NRE::IO::FileStream::operator=</a>(FileStream const &amp;f)=delete</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php">NRE::IO::FileStream</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#aeba406b1cbfa2d9a0f21882e8e1815d6">NRE::IO::FileStream::operator=</a>(FileStream &amp;&amp;f)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php">NRE::IO::FileStream</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a94972246304fc4df0e029d0f657b86ae">NRE::IO::File::operator=</a>(File const &amp;f)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">NRE::IO::File</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a980fc1b961a9974d6331991af204cc3d">NRE::IO::File::operator=</a>(File &amp;&amp;f)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">NRE::IO::File</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#a5e95195616de0936b5c54377b7685e6c">NRE::IO::InputStream::operator=</a>(InputStream const &amp;i)=delete</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">NRE::IO::InputStream</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#ae268a182a6e21b17ccb8f6e2af98d2b2">NRE::IO::InputStream::operator=</a>(InputStream &amp;&amp;i)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">NRE::IO::InputStream</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#a4863ac832c227dc838e4d8a74db97c6a">read</a>(T &amp;object)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">NRE::IO::InputStream</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#af91eeb1fc3eb2a8ea3c623d0d140e6a4">readLine</a>(Utility::String &amp;line)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">NRE::IO::InputStream</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#a7365375159cb13f7d4d1004e39a622c3">seekBegin</a>(size_t offset=0)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">NRE::IO::InputStream</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#ae0fbdbcce3b727547ad94f035608906d">seekEnd</a>(size_t offset=0)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">NRE::IO::InputStream</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a1414f962cf4bcae9450b66643f8e3d67">setPath</a>(Utility::String const &amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">NRE::IO::File</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a0137a4cc6e43c091bc88e485eb29b91f">toString</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">NRE::IO::File</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a915cdede01e62ea1c8a0a970480a53af">~File</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">NRE::IO::File</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#a85b97b37c6487fa16924773adcc90d12">~FileStream</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php">NRE::IO::FileStream</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php#a01cc8f3e1193bfa3167c5b7d7f85a9d6">~InputFile</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php">NRE::IO::InputFile</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#a6640a5cd0ec7f081452aea53bde44f34">~InputStream</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php">NRE::IO::InputStream</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
