<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-IO: NRE::IO::BinaryInputStream Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>IO</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">BinaryInputStream</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_i_o_1_1_binary_input_stream-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::IO::BinaryInputStream Class Reference<span class="mlabels"><span class="mlabel">abstract</span></span></div>  </div>
</div><!--header-->
<div class="contents">

<p>Base interface for binary input related stream.  
 <a href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___binary_input_stream_8hpp_source.php">NRE_BinaryInputStream.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::IO::BinaryInputStream:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_i_o_1_1_binary_input_stream.png" usemap="#NRE::IO::BinaryInputStream_map" alt=""/>
  <map id="NRE::IO::BinaryInputStream_map" name="NRE::IO::BinaryInputStream_map">
<area href="class_n_r_e_1_1_i_o_1_1_binary_input_file.php" title="Manage binary input file stream. " alt="NRE::IO::BinaryInputFile" shape="rect" coords="0,56,165,80"/>
<area href="class_n_r_e_1_1_i_o_1_1_binary_i_o_file.php" title="Manage Binary Input-Output file stream. " alt="NRE::IO::BinaryIOFile" shape="rect" coords="175,56,340,80"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a63da2d140ad77e663a65076df5cdb944"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#a63da2d140ad77e663a65076df5cdb944">BinaryInputStream</a> ()=default</td></tr>
<tr class="separator:a63da2d140ad77e663a65076df5cdb944"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0bd9164643ad43201392cc72972e93cd"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#a0bd9164643ad43201392cc72972e93cd">BinaryInputStream</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">BinaryInputStream</a> const &amp;i)=delete</td></tr>
<tr class="separator:a0bd9164643ad43201392cc72972e93cd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abd129bd9d294a131f2aa26a51815ff8a"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#abd129bd9d294a131f2aa26a51815ff8a">BinaryInputStream</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">BinaryInputStream</a> &amp;&amp;i)=default</td></tr>
<tr class="separator:abd129bd9d294a131f2aa26a51815ff8a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac39b3d01a85995cebacdfa64a1a1b588"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#ac39b3d01a85995cebacdfa64a1a1b588">~BinaryInputStream</a> ()=default</td></tr>
<tr class="separator:ac39b3d01a85995cebacdfa64a1a1b588"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a746061ba00a5188ddf5d55143c7aed4b"><td class="memItemLeft" align="right" valign="top">virtual std::fstream &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#a746061ba00a5188ddf5d55143c7aed4b">getStream</a> ()=0</td></tr>
<tr class="separator:a746061ba00a5188ddf5d55143c7aed4b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acec53ec7e9fa9adb1b7ad8b50f7364c8"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:acec53ec7e9fa9adb1b7ad8b50f7364c8"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#acec53ec7e9fa9adb1b7ad8b50f7364c8">readBinary</a> (T &amp;object, size_t sizeInBytes)</td></tr>
<tr class="separator:acec53ec7e9fa9adb1b7ad8b50f7364c8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa72a8c1f1905ca197325afbcba4cd7ed"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">BinaryInputStream</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#aa72a8c1f1905ca197325afbcba4cd7ed">operator=</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">BinaryInputStream</a> const &amp;i)=delete</td></tr>
<tr class="separator:aa72a8c1f1905ca197325afbcba4cd7ed"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a44f734da5a46ef599468ee24b947b659"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">BinaryInputStream</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#a44f734da5a46ef599468ee24b947b659">operator=</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">BinaryInputStream</a> &amp;&amp;i)=default</td></tr>
<tr class="separator:a44f734da5a46ef599468ee24b947b659"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Base interface for binary input related stream. </p>
<p><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php" title="Base interface for binary input related stream. ">BinaryInputStream</a> </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a63da2d140ad77e663a65076df5cdb944"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::IO::BinaryInputStream::BinaryInputStream </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Default constructor </p>

</div>
</div>
<a class="anchor" id="a0bd9164643ad43201392cc72972e93cd"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::IO::BinaryInputStream::BinaryInputStream </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">BinaryInputStream</a> const &amp;&#160;</td>
          <td class="paramname"><em>i</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the binary input stream to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="abd129bd9d294a131f2aa26a51815ff8a"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::IO::BinaryInputStream::BinaryInputStream </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">BinaryInputStream</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>i</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move i into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the binary input stream to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ac39b3d01a85995cebacdfa64a1a1b588"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual NRE::IO::BinaryInputStream::~BinaryInputStream </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">virtual</span><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php" title="Base interface for binary input related stream. ">BinaryInputStream</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a746061ba00a5188ddf5d55143c7aed4b"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual std::fstream&amp; NRE::IO::BinaryInputStream::getStream </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">pure virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the file's stream </dd></dl>

<p>Implemented in <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_i_o_file.php#ae312212af94dc55296cbeec60806b2bc">NRE::IO::BinaryIOFile</a>, and <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_file.php#abd74b00ec06cb5c1c828a68024af2f2a">NRE::IO::BinaryInputFile</a>.</p>

</div>
</div>
<a class="anchor" id="aa72a8c1f1905ca197325afbcba4cd7ed"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">BinaryInputStream</a>&amp; NRE::IO::BinaryInputStream::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">BinaryInputStream</a> const &amp;&#160;</td>
          <td class="paramname"><em>i</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy assignment forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the binary input stream to copy </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a44f734da5a46ef599468ee24b947b659"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">BinaryInputStream</a>&amp; NRE::IO::BinaryInputStream::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php">BinaryInputStream</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>i</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move assignment of i into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the binary input stream to move </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="acec53ec7e9fa9adb1b7ad8b50f7364c8"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::IO::BinaryInputStream::readBinary </td>
          <td>(</td>
          <td class="paramtype">T &amp;&#160;</td>
          <td class="paramname"><em>object</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">size_t&#160;</td>
          <td class="paramname"><em>sizeInBytes</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Read a given number of bytes into the passed data from the file stream </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">object</td><td>the data to store the read return </td></tr>
    <tr><td class="paramname">sizeInBytes</td><td>the number of bytes to read </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-IO/src/IO/FileStream/BinaryInput/Stream/<a class="el" href="_n_r_e___binary_input_stream_8hpp_source.php">NRE_BinaryInputStream.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
