<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-IO: NRE::IO::File Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>IO</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_i_o_1_1_file-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::IO::File Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Manage a file path and ensure that's the file exist before accessing it.  
 <a href="class_n_r_e_1_1_i_o_1_1_file.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___file_8hpp_source.php">NRE_File.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::IO::File:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_i_o_1_1_file.png" usemap="#NRE::IO::File_map" alt=""/>
  <map id="NRE::IO::File_map" name="NRE::IO::File_map">
<area href="class_n_r_e_1_1_i_o_1_1_file_stream.php" title="The base interface for Input, Output and IO file. " alt="NRE::IO::FileStream" shape="rect" coords="167,56,324,80"/>
<area href="class_n_r_e_1_1_i_o_1_1_input_file.php" title="Manage input file stream. " alt="NRE::IO::InputFile" shape="rect" coords="0,112,157,136"/>
<area href="class_n_r_e_1_1_i_o_1_1_i_o_file.php" title="Manage Input-Output file stream. " alt="NRE::IO::IOFile" shape="rect" coords="167,112,324,136"/>
<area href="class_n_r_e_1_1_i_o_1_1_output_file.php" title="Manage output file stream. " alt="NRE::IO::OutputFile" shape="rect" coords="334,112,491,136"/>
<area href="class_n_r_e_1_1_i_o_1_1_binary_input_file.php" title="Manage binary input file stream. " alt="NRE::IO::BinaryInputFile" shape="rect" coords="0,168,157,192"/>
<area href="class_n_r_e_1_1_i_o_1_1_binary_i_o_file.php" title="Manage Binary Input-Output file stream. " alt="NRE::IO::BinaryIOFile" shape="rect" coords="167,168,324,192"/>
<area href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php" title="Manage binary output file stream. " alt="NRE::IO::BinaryOutputFile" shape="rect" coords="334,168,491,192"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:ae31e8c433fdbda9a37130168b5fb2858"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#ae31e8c433fdbda9a37130168b5fb2858">File</a> ()=default</td></tr>
<tr class="separator:ae31e8c433fdbda9a37130168b5fb2858"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a71392564fdd4bdcbad2a9dec89a0aee1"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a71392564fdd4bdcbad2a9dec89a0aee1">File</a> (Utility::String const &amp;p)</td></tr>
<tr class="separator:a71392564fdd4bdcbad2a9dec89a0aee1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af49f63c9e981ee77ebe0d71caa65cfad"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#af49f63c9e981ee77ebe0d71caa65cfad">File</a> (char const p[])</td></tr>
<tr class="separator:af49f63c9e981ee77ebe0d71caa65cfad"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ada63f8f00e27c1d6ec5ea6f09b5f9c75"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#ada63f8f00e27c1d6ec5ea6f09b5f9c75">File</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> const &amp;f)=default</td></tr>
<tr class="separator:ada63f8f00e27c1d6ec5ea6f09b5f9c75"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9860259838f1a163a7a931b3cbae3174"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a9860259838f1a163a7a931b3cbae3174">File</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> &amp;&amp;f)=default</td></tr>
<tr class="separator:a9860259838f1a163a7a931b3cbae3174"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a915cdede01e62ea1c8a0a970480a53af"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a915cdede01e62ea1c8a0a970480a53af">~File</a> ()=default</td></tr>
<tr class="separator:a915cdede01e62ea1c8a0a970480a53af"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6ff1d432623961e08ed64eeb97d547c7"><td class="memItemLeft" align="right" valign="top">Utility::String const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a6ff1d432623961e08ed64eeb97d547c7">getPath</a> () const </td></tr>
<tr class="separator:a6ff1d432623961e08ed64eeb97d547c7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1414f962cf4bcae9450b66643f8e3d67"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a1414f962cf4bcae9450b66643f8e3d67">setPath</a> (Utility::String const &amp;p)</td></tr>
<tr class="separator:a1414f962cf4bcae9450b66643f8e3d67"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae955f8bc07d667649e7f045c2bbbef49"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#ae955f8bc07d667649e7f045c2bbbef49">exist</a> () const </td></tr>
<tr class="separator:ae955f8bc07d667649e7f045c2bbbef49"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a94972246304fc4df0e029d0f657b86ae"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a94972246304fc4df0e029d0f657b86ae">operator=</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> const &amp;f)=default</td></tr>
<tr class="separator:a94972246304fc4df0e029d0f657b86ae"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a980fc1b961a9974d6331991af204cc3d"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a980fc1b961a9974d6331991af204cc3d">operator=</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> &amp;&amp;f)=default</td></tr>
<tr class="separator:a980fc1b961a9974d6331991af204cc3d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af5e129d3ca95bbc6db8c43ad84aaaf6c"><td class="memItemLeft" align="right" valign="top">Utility::String&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#af5e129d3ca95bbc6db8c43ad84aaaf6c">operator+</a> (Utility::String const &amp;s) const </td></tr>
<tr class="separator:af5e129d3ca95bbc6db8c43ad84aaaf6c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2009e071a45be3a88bcfc03bd7868b50"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a2009e071a45be3a88bcfc03bd7868b50">operator+</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> const &amp;f) const </td></tr>
<tr class="separator:a2009e071a45be3a88bcfc03bd7868b50"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0137a4cc6e43c091bc88e485eb29b91f"><td class="memItemLeft" align="right" valign="top">Utility::String const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a0137a4cc6e43c091bc88e485eb29b91f">toString</a> () const </td></tr>
<tr class="separator:a0137a4cc6e43c091bc88e485eb29b91f"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Manage a file path and ensure that's the file exist before accessing it. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="ae31e8c433fdbda9a37130168b5fb2858"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::IO::File::File </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Default constructor </p>

</div>
</div>
<a class="anchor" id="a71392564fdd4bdcbad2a9dec89a0aee1"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::IO::File::File </td>
          <td>(</td>
          <td class="paramtype">Utility::String const &amp;&#160;</td>
          <td class="paramname"><em>p</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct a <a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php" title="Manage a file path and ensure that&#39;s the file exist before accessing it. ">File</a> with the given path </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">p</td><td>the file's path </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="af49f63c9e981ee77ebe0d71caa65cfad"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::IO::File::File </td>
          <td>(</td>
          <td class="paramtype">char const&#160;</td>
          <td class="paramname"><em>p</em>[]</td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct a <a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php" title="Manage a file path and ensure that&#39;s the file exist before accessing it. ">File</a> from a char array for compatibility </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">p</td><td>the char array </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ada63f8f00e27c1d6ec5ea6f09b5f9c75"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::IO::File::File </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> const &amp;&#160;</td>
          <td class="paramname"><em>f</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy f into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">f</td><td>the file to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a9860259838f1a163a7a931b3cbae3174"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::IO::File::File </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>f</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move f into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">f</td><td>the file to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a915cdede01e62ea1c8a0a970480a53af"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::IO::File::~File </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php" title="Manage a file path and ensure that&#39;s the file exist before accessing it. ">File</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="ae955f8bc07d667649e7f045c2bbbef49"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::IO::File::exist </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Open the file with standard lib and test if it open correctly </p><dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a class="anchor" id="a6ff1d432623961e08ed64eeb97d547c7"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Utility::String const&amp; NRE::IO::File::getPath </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the file's path </dd></dl>

</div>
</div>
<a class="anchor" id="af5e129d3ca95bbc6db8c43ad84aaaf6c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Utility::String NRE::IO::File::operator+ </td>
          <td>(</td>
          <td class="paramtype">Utility::String const &amp;&#160;</td>
          <td class="paramname"><em>s</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Compute the string with the file path and s concatenated </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">s</td><td>the string to add </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the concatenated string </dd></dl>

</div>
</div>
<a class="anchor" id="a2009e071a45be3a88bcfc03bd7868b50"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> NRE::IO::File::operator+ </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> const &amp;&#160;</td>
          <td class="paramname"><em>f</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Compute the file resulting in the concatenation of 2 file path </p><dl class="section return"><dt>Returns</dt><dd>the computed file </dd></dl>

</div>
</div>
<a class="anchor" id="a94972246304fc4df0e029d0f657b86ae"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a>&amp; NRE::IO::File::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> const &amp;&#160;</td>
          <td class="paramname"><em>f</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy assignment of f into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">f</td><td>the file to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a980fc1b961a9974d6331991af204cc3d"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a>&amp; NRE::IO::File::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>f</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move assignment of f into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">f</td><td>the file to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a1414f962cf4bcae9450b66643f8e3d67"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::IO::File::setPath </td>
          <td>(</td>
          <td class="paramtype">Utility::String const &amp;&#160;</td>
          <td class="paramname"><em>p</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set the file's path </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">p</td><td>the new file's path </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a0137a4cc6e43c091bc88e485eb29b91f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Utility::String const&amp; NRE::IO::File::toString </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Convert the file into a string </p><dl class="section return"><dt>Returns</dt><dd>the converted file </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-IO/src/IO/File/<a class="el" href="_n_r_e___file_8hpp_source.php">NRE_File.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
