<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-IO: NRE::IO::BinaryOutputFile Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>IO</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php">BinaryOutputFile</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_i_o_1_1_binary_output_file-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::IO::BinaryOutputFile Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Manage binary output file stream.  
 <a href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___binary_output_file_8hpp_source.php">NRE_BinaryOutputFile.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::IO::BinaryOutputFile:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_i_o_1_1_binary_output_file.png" usemap="#NRE::IO::BinaryOutputFile_map" alt=""/>
  <map id="NRE::IO::BinaryOutputFile_map" name="NRE::IO::BinaryOutputFile_map">
<area href="class_n_r_e_1_1_i_o_1_1_output_file.php" title="Manage output file stream. " alt="NRE::IO::OutputFile" shape="rect" coords="92,112,267,136"/>
<area href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php" title="Base interface for binary output related stream. " alt="NRE::IO::BinaryOutputStream" shape="rect" coords="277,112,452,136"/>
<area href="class_n_r_e_1_1_i_o_1_1_file_stream.php" title="The base interface for Input, Output and IO file. " alt="NRE::IO::FileStream" shape="rect" coords="0,56,175,80"/>
<area href="class_n_r_e_1_1_i_o_1_1_output_stream.php" title="Base interface for output related stream. " alt="NRE::IO::OutputStream" shape="rect" coords="185,56,360,80"/>
<area href="class_n_r_e_1_1_i_o_1_1_file.php" title="Manage a file path and ensure that&#39;s the file exist before accessing it. " alt="NRE::IO::File" shape="rect" coords="0,0,175,24"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a871470082e331d4c4de52225fbdd6d5d"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php#a871470082e331d4c4de52225fbdd6d5d">BinaryOutputFile</a> ()=delete</td></tr>
<tr class="separator:a871470082e331d4c4de52225fbdd6d5d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a96cc5fe5e9c01f1460ed8ffe96f7c719"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php#a96cc5fe5e9c01f1460ed8ffe96f7c719">BinaryOutputFile</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> const &amp;p)</td></tr>
<tr class="separator:a96cc5fe5e9c01f1460ed8ffe96f7c719"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a51e7293c00bcbda8bb38ed2a500e28ee"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php#a51e7293c00bcbda8bb38ed2a500e28ee">BinaryOutputFile</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php">BinaryOutputFile</a> &amp;&amp;o)=default</td></tr>
<tr class="separator:a51e7293c00bcbda8bb38ed2a500e28ee"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a799573c27d504e89bd7512a57caee395"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php#a799573c27d504e89bd7512a57caee395">~BinaryOutputFile</a> ()=default</td></tr>
<tr class="separator:a799573c27d504e89bd7512a57caee395"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aab5124d17d117c920d5f8ffe48e0226a"><td class="memItemLeft" align="right" valign="top">std::ios_base::openmode&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php#aab5124d17d117c920d5f8ffe48e0226a">getMode</a> () const override</td></tr>
<tr class="separator:aab5124d17d117c920d5f8ffe48e0226a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a226f850a5fc4d714d97c5688e94c1d7e"><td class="memItemLeft" align="right" valign="top">std::fstream &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php#a226f850a5fc4d714d97c5688e94c1d7e">getStream</a> () override</td></tr>
<tr class="separator:a226f850a5fc4d714d97c5688e94c1d7e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0e11dce33943c88dbcce066995fb67e2"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php">BinaryOutputFile</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php#a0e11dce33943c88dbcce066995fb67e2">operator=</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php">BinaryOutputFile</a> &amp;&amp;o)</td></tr>
<tr class="separator:a0e11dce33943c88dbcce066995fb67e2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_class_n_r_e_1_1_i_o_1_1_output_file"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_class_n_r_e_1_1_i_o_1_1_output_file')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="class_n_r_e_1_1_i_o_1_1_output_file.php">NRE::IO::OutputFile</a></td></tr>
<tr class="memitem:a27886f61f81fa7131725eab50cc3655e inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_file"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_file.php#a27886f61f81fa7131725eab50cc3655e">OutputFile</a> ()=delete</td></tr>
<tr class="separator:a27886f61f81fa7131725eab50cc3655e inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_file"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1c607062c5a45f57931d46e225bed7a1 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_file"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_file.php#a1c607062c5a45f57931d46e225bed7a1">OutputFile</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> const &amp;p)</td></tr>
<tr class="separator:a1c607062c5a45f57931d46e225bed7a1 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_file"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acefaded29c0882612f591c31b906ec79 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_file"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_file.php#acefaded29c0882612f591c31b906ec79">OutputFile</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_output_file.php">OutputFile</a> &amp;&amp;o)=default</td></tr>
<tr class="separator:acefaded29c0882612f591c31b906ec79 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_file"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a247e5ee5620e365af61372f0bea51eda inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_file"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_file.php#a247e5ee5620e365af61372f0bea51eda">~OutputFile</a> ()=default</td></tr>
<tr class="separator:a247e5ee5620e365af61372f0bea51eda inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_file"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a05d4699bd6aaca11eedc5e398a2ba4f6 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_file"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_file.php">OutputFile</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_file.php#a05d4699bd6aaca11eedc5e398a2ba4f6">operator=</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_output_file.php">OutputFile</a> &amp;&amp;o)=default</td></tr>
<tr class="separator:a05d4699bd6aaca11eedc5e398a2ba4f6 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_file"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php">NRE::IO::FileStream</a></td></tr>
<tr class="memitem:a7bef175fe08cc377c872103f61864859 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#a7bef175fe08cc377c872103f61864859">FileStream</a> ()=delete</td></tr>
<tr class="separator:a7bef175fe08cc377c872103f61864859 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a984be898303f6344d5c15efb5fa4e886 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#a984be898303f6344d5c15efb5fa4e886">FileStream</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> const &amp;p)</td></tr>
<tr class="separator:a984be898303f6344d5c15efb5fa4e886 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afc239902cef34ecfd890cf69a5172c6d inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#afc239902cef34ecfd890cf69a5172c6d">FileStream</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php">FileStream</a> const &amp;f)=delete</td></tr>
<tr class="separator:afc239902cef34ecfd890cf69a5172c6d inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae9637c1e640b0dacecad04bf957a91f0 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#ae9637c1e640b0dacecad04bf957a91f0">FileStream</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php">FileStream</a> &amp;&amp;f)=default</td></tr>
<tr class="separator:ae9637c1e640b0dacecad04bf957a91f0 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a85b97b37c6487fa16924773adcc90d12 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#a85b97b37c6487fa16924773adcc90d12">~FileStream</a> ()=default</td></tr>
<tr class="separator:a85b97b37c6487fa16924773adcc90d12 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6cb9f46d893839b4518cc86b3afe2178 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#a6cb9f46d893839b4518cc86b3afe2178">isOpen</a> () const </td></tr>
<tr class="separator:a6cb9f46d893839b4518cc86b3afe2178 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a24979d0affac7992e181820b881941eb inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#a24979d0affac7992e181820b881941eb">open</a> ()</td></tr>
<tr class="separator:a24979d0affac7992e181820b881941eb inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af0677c0d90634a88472f629567ca5238 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#af0677c0d90634a88472f629567ca5238">openEmpty</a> ()</td></tr>
<tr class="separator:af0677c0d90634a88472f629567ca5238 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a357c757b87bc7876f0b1f2fb7f96edb1 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php">FileStream</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#a357c757b87bc7876f0b1f2fb7f96edb1">operator=</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php">FileStream</a> const &amp;f)=delete</td></tr>
<tr class="separator:a357c757b87bc7876f0b1f2fb7f96edb1 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aeba406b1cbfa2d9a0f21882e8e1815d6 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php">FileStream</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#aeba406b1cbfa2d9a0f21882e8e1815d6">operator=</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php">FileStream</a> &amp;&amp;f)=default</td></tr>
<tr class="separator:aeba406b1cbfa2d9a0f21882e8e1815d6 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_class_n_r_e_1_1_i_o_1_1_file')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">NRE::IO::File</a></td></tr>
<tr class="memitem:ae31e8c433fdbda9a37130168b5fb2858 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#ae31e8c433fdbda9a37130168b5fb2858">File</a> ()=default</td></tr>
<tr class="separator:ae31e8c433fdbda9a37130168b5fb2858 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a71392564fdd4bdcbad2a9dec89a0aee1 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a71392564fdd4bdcbad2a9dec89a0aee1">File</a> (Utility::String const &amp;p)</td></tr>
<tr class="separator:a71392564fdd4bdcbad2a9dec89a0aee1 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af49f63c9e981ee77ebe0d71caa65cfad inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#af49f63c9e981ee77ebe0d71caa65cfad">File</a> (char const p[])</td></tr>
<tr class="separator:af49f63c9e981ee77ebe0d71caa65cfad inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ada63f8f00e27c1d6ec5ea6f09b5f9c75 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#ada63f8f00e27c1d6ec5ea6f09b5f9c75">File</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> const &amp;f)=default</td></tr>
<tr class="separator:ada63f8f00e27c1d6ec5ea6f09b5f9c75 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9860259838f1a163a7a931b3cbae3174 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a9860259838f1a163a7a931b3cbae3174">File</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> &amp;&amp;f)=default</td></tr>
<tr class="separator:a9860259838f1a163a7a931b3cbae3174 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a915cdede01e62ea1c8a0a970480a53af inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a915cdede01e62ea1c8a0a970480a53af">~File</a> ()=default</td></tr>
<tr class="separator:a915cdede01e62ea1c8a0a970480a53af inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6ff1d432623961e08ed64eeb97d547c7 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memItemLeft" align="right" valign="top">Utility::String const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a6ff1d432623961e08ed64eeb97d547c7">getPath</a> () const </td></tr>
<tr class="separator:a6ff1d432623961e08ed64eeb97d547c7 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1414f962cf4bcae9450b66643f8e3d67 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a1414f962cf4bcae9450b66643f8e3d67">setPath</a> (Utility::String const &amp;p)</td></tr>
<tr class="separator:a1414f962cf4bcae9450b66643f8e3d67 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae955f8bc07d667649e7f045c2bbbef49 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#ae955f8bc07d667649e7f045c2bbbef49">exist</a> () const </td></tr>
<tr class="separator:ae955f8bc07d667649e7f045c2bbbef49 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a94972246304fc4df0e029d0f657b86ae inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a94972246304fc4df0e029d0f657b86ae">operator=</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> const &amp;f)=default</td></tr>
<tr class="separator:a94972246304fc4df0e029d0f657b86ae inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a980fc1b961a9974d6331991af204cc3d inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a980fc1b961a9974d6331991af204cc3d">operator=</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> &amp;&amp;f)=default</td></tr>
<tr class="separator:a980fc1b961a9974d6331991af204cc3d inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af5e129d3ca95bbc6db8c43ad84aaaf6c inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memItemLeft" align="right" valign="top">Utility::String&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#af5e129d3ca95bbc6db8c43ad84aaaf6c">operator+</a> (Utility::String const &amp;s) const </td></tr>
<tr class="separator:af5e129d3ca95bbc6db8c43ad84aaaf6c inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2009e071a45be3a88bcfc03bd7868b50 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a2009e071a45be3a88bcfc03bd7868b50">operator+</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> const &amp;f) const </td></tr>
<tr class="separator:a2009e071a45be3a88bcfc03bd7868b50 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0137a4cc6e43c091bc88e485eb29b91f inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memItemLeft" align="right" valign="top">Utility::String const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a0137a4cc6e43c091bc88e485eb29b91f">toString</a> () const </td></tr>
<tr class="separator:a0137a4cc6e43c091bc88e485eb29b91f inherit pub_methods_class_n_r_e_1_1_i_o_1_1_file"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">NRE::IO::OutputStream</a></td></tr>
<tr class="memitem:a1efcdc994b4d8d955460a813d525bf9d inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a1efcdc994b4d8d955460a813d525bf9d">OutputStream</a> ()=default</td></tr>
<tr class="separator:a1efcdc994b4d8d955460a813d525bf9d inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a58f80840a0b7cd9d76a732c0df1fce60 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a58f80840a0b7cd9d76a732c0df1fce60">OutputStream</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a> const &amp;o)=delete</td></tr>
<tr class="separator:a58f80840a0b7cd9d76a732c0df1fce60 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7113e072849339312d22fb688dd18476 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a7113e072849339312d22fb688dd18476">OutputStream</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a> &amp;&amp;o)=default</td></tr>
<tr class="separator:a7113e072849339312d22fb688dd18476 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab93399476f8933a7062c9ab3c0db0e05 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#ab93399476f8933a7062c9ab3c0db0e05">~OutputStream</a> ()=default</td></tr>
<tr class="separator:ab93399476f8933a7062c9ab3c0db0e05 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4865057a0271a36ec3cde6e76282ebfc inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td class="memItemLeft" align="right" valign="top">std::streampos&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a4865057a0271a36ec3cde6e76282ebfc">getPosition</a> ()</td></tr>
<tr class="separator:a4865057a0271a36ec3cde6e76282ebfc inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2347d2de8cf213aee37148c25c5bdf6c inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:a2347d2de8cf213aee37148c25c5bdf6c inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a2347d2de8cf213aee37148c25c5bdf6c">write</a> (T const &amp;object)</td></tr>
<tr class="separator:a2347d2de8cf213aee37148c25c5bdf6c inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab17afff8528ac5d7ba2fd8a5577022e2 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#ab17afff8528ac5d7ba2fd8a5577022e2">seekBegin</a> (size_t offset=0)</td></tr>
<tr class="separator:ab17afff8528ac5d7ba2fd8a5577022e2 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a78c55f5724508b1cd92aea071306029d inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a78c55f5724508b1cd92aea071306029d">seekEnd</a> (size_t offset=0)</td></tr>
<tr class="separator:a78c55f5724508b1cd92aea071306029d inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a19aca25943b90833a09c633f2ad4a097 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a19aca25943b90833a09c633f2ad4a097">operator=</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a> const &amp;o)=delete</td></tr>
<tr class="separator:a19aca25943b90833a09c633f2ad4a097 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adedec60a6e3842e33bbd650981339d16 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#adedec60a6e3842e33bbd650981339d16">operator=</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php">OutputStream</a> &amp;&amp;o)=default</td></tr>
<tr class="separator:adedec60a6e3842e33bbd650981339d16 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_output_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_class_n_r_e_1_1_i_o_1_1_binary_output_stream"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_class_n_r_e_1_1_i_o_1_1_binary_output_stream')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php">NRE::IO::BinaryOutputStream</a></td></tr>
<tr class="memitem:af82285fba8d579c92c13a6ab8c6ea1f8 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_binary_output_stream"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php#af82285fba8d579c92c13a6ab8c6ea1f8">BinaryOutputStream</a> ()=default</td></tr>
<tr class="separator:af82285fba8d579c92c13a6ab8c6ea1f8 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_binary_output_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6d1a9da85a63f9db2b63bb995245168f inherit pub_methods_class_n_r_e_1_1_i_o_1_1_binary_output_stream"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php#a6d1a9da85a63f9db2b63bb995245168f">BinaryOutputStream</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php">BinaryOutputStream</a> const &amp;o)=delete</td></tr>
<tr class="separator:a6d1a9da85a63f9db2b63bb995245168f inherit pub_methods_class_n_r_e_1_1_i_o_1_1_binary_output_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adb3b7cfe27fe65b3995fffd16ac3960d inherit pub_methods_class_n_r_e_1_1_i_o_1_1_binary_output_stream"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php#adb3b7cfe27fe65b3995fffd16ac3960d">BinaryOutputStream</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php">BinaryOutputStream</a> &amp;&amp;o)=default</td></tr>
<tr class="separator:adb3b7cfe27fe65b3995fffd16ac3960d inherit pub_methods_class_n_r_e_1_1_i_o_1_1_binary_output_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa3465fcc7636a59bbe506b55a2c749b4 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_binary_output_stream"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php#aa3465fcc7636a59bbe506b55a2c749b4">~BinaryOutputStream</a> ()=default</td></tr>
<tr class="separator:aa3465fcc7636a59bbe506b55a2c749b4 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_binary_output_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a82c8c1174443122100e617f153989071 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_binary_output_stream"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:a82c8c1174443122100e617f153989071 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_binary_output_stream"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php#a82c8c1174443122100e617f153989071">writeBinary</a> (T const &amp;object, std::size_t sizeInBytes)</td></tr>
<tr class="separator:a82c8c1174443122100e617f153989071 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_binary_output_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a29955b656accd131c03a1e3e2c7f352c inherit pub_methods_class_n_r_e_1_1_i_o_1_1_binary_output_stream"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php">BinaryOutputStream</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php#a29955b656accd131c03a1e3e2c7f352c">operator=</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php">BinaryOutputStream</a> const &amp;o)=delete</td></tr>
<tr class="separator:a29955b656accd131c03a1e3e2c7f352c inherit pub_methods_class_n_r_e_1_1_i_o_1_1_binary_output_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a22c3314cce0571099077300cd2135832 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_binary_output_stream"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php">BinaryOutputStream</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php#a22c3314cce0571099077300cd2135832">operator=</a> (<a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php">BinaryOutputStream</a> &amp;&amp;o)=default</td></tr>
<tr class="separator:a22c3314cce0571099077300cd2135832 inherit pub_methods_class_n_r_e_1_1_i_o_1_1_binary_output_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="inherited"></a>
Additional Inherited Members</h2></td></tr>
<tr class="inherit_header pro_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td colspan="2" onclick="javascript:toggleInherit('pro_methods_class_n_r_e_1_1_i_o_1_1_file_stream')"><img src="closed.png" alt="-"/>&#160;Protected Member Functions inherited from <a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php">NRE::IO::FileStream</a></td></tr>
<tr class="memitem:a36c7a3ca5e4e79e6f706577d04d3bffe inherit pro_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memItemLeft" align="right" valign="top">std::fstream &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#a36c7a3ca5e4e79e6f706577d04d3bffe">getStream</a> ()</td></tr>
<tr class="separator:a36c7a3ca5e4e79e6f706577d04d3bffe inherit pro_methods_class_n_r_e_1_1_i_o_1_1_file_stream"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Manage binary output file stream. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a871470082e331d4c4de52225fbdd6d5d"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::IO::BinaryOutputFile::BinaryOutputFile </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Default Constructor </p>

</div>
</div>
<a class="anchor" id="a96cc5fe5e9c01f1460ed8ffe96f7c719"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::IO::BinaryOutputFile::BinaryOutputFile </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php">File</a> const &amp;&#160;</td>
          <td class="paramname"><em>p</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct an binary output file stream with a given file's path </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">p</td><td>the file's stream path </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a51e7293c00bcbda8bb38ed2a500e28ee"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::IO::BinaryOutputFile::BinaryOutputFile </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php">BinaryOutputFile</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>o</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move o into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">o</td><td>the binary output file to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a799573c27d504e89bd7512a57caee395"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::IO::BinaryOutputFile::~BinaryOutputFile </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php" title="Manage binary output file stream. ">BinaryOutputFile</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="aab5124d17d117c920d5f8ffe48e0226a"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::ios_base::openmode NRE::IO::BinaryOutputFile::getMode </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">override</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the binary output file stream opening mode </dd></dl>

<p>Reimplemented from <a class="el" href="class_n_r_e_1_1_i_o_1_1_output_file.php#a8878a1a46a6487059844d6dcf495c3a3">NRE::IO::OutputFile</a>.</p>

</div>
</div>
<a class="anchor" id="a226f850a5fc4d714d97c5688e94c1d7e"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::fstream&amp; NRE::IO::BinaryOutputFile::getStream </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">override</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the binary output file's stream </dd></dl>

<p>Implements <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php#afc14dff50cead68bef5210966d3e5f58">NRE::IO::BinaryOutputStream</a>.</p>

</div>
</div>
<a class="anchor" id="a0e11dce33943c88dbcce066995fb67e2"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php">BinaryOutputFile</a>&amp; NRE::IO::BinaryOutputFile::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php">BinaryOutputFile</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>o</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Move assignment of i into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">o</td><td>the binary output file to move </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-IO/src/IO/FileStream/BinaryOutput/File/<a class="el" href="_n_r_e___binary_output_file_8hpp_source.php">NRE_BinaryOutputFile.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
