<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-IO: File List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li class="current"><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">File List</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock">Here is a list of all documented files with brief descriptions:</div><div class="directory">
<div class="levels">[detail level <span onclick="javascript:toggleLevel(1);">1</span><span onclick="javascript:toggleLevel(2);">2</span><span onclick="javascript:toggleLevel(3);">3</span><span onclick="javascript:toggleLevel(4);">4</span><span onclick="javascript:toggleLevel(5);">5</span><span onclick="javascript:toggleLevel(6);">6</span>]</div><table class="directory">
<tr id="row_0_" class="even"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_0_" class="arrow" onclick="toggleFolder('0_')">&#9660;</span><span id="img_0_" class="iconfopen" onclick="toggleFolder('0_')">&#160;</span><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php" target="_self">src</a></td><td class="desc"></td></tr>
<tr id="row_0_0_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_0_0_" class="arrow" onclick="toggleFolder('0_0_')">&#9660;</span><span id="img_0_0_" class="iconfopen" onclick="toggleFolder('0_0_')">&#160;</span><a class="el" href="dir_8325968175170435003107496b1cfdde.php" target="_self">Exception</a></td><td class="desc"></td></tr>
<tr id="row_0_0_0_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><a href="_n_r_e___file_not_existing_exception_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___file_not_existing_exception_8hpp.php" target="_self">NRE_FileNotExistingException.hpp</a></td><td class="desc">Declaration of System's API's Object : FileNotExistingException </td></tr>
<tr id="row_0_0_1_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><a href="_n_r_e___file_not_opening_exception_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___file_not_opening_exception_8hpp.php" target="_self">NRE_FileNotOpeningException.hpp</a></td><td class="desc">Declaration of System's API's Object : FileNotOpeningException </td></tr>
<tr id="row_0_0_2_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><a href="_n_r_e___i_o_exception_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___i_o_exception_8hpp.php" target="_self">NRE_IOException.hpp</a></td><td class="desc">Declaration of System's API's Object : IOException </td></tr>
<tr id="row_0_1_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_0_1_" class="arrow" onclick="toggleFolder('0_1_')">&#9660;</span><span id="img_0_1_" class="iconfopen" onclick="toggleFolder('0_1_')">&#160;</span><a class="el" href="dir_0bb4bacb73d7f86c6a963ab22a4f5c20.php" target="_self">Header</a></td><td class="desc"></td></tr>
<tr id="row_0_1_0_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><a href="_n_r_e___exception_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___exception_8hpp.php" target="_self">NRE_Exception.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_i_o.php" title="IO&#39;s API. ">IO</a>'s API's <a class="el" href="namespace_exception.php" title="Utility&#39;s API. ">Exception</a> Header </td></tr>
<tr id="row_0_1_1_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><a href="_n_r_e___i_o_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___i_o_8hpp.php" target="_self">NRE_IO.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_i_o.php" title="IO&#39;s API. ">IO</a>'s API's Header </td></tr>
<tr id="row_0_2_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_0_2_" class="arrow" onclick="toggleFolder('0_2_')">&#9660;</span><span id="img_0_2_" class="iconfopen" onclick="toggleFolder('0_2_')">&#160;</span><a class="el" href="dir_fae119eb913a40fe8ed97cde8b98911e.php" target="_self">IO</a></td><td class="desc"></td></tr>
<tr id="row_0_2_0_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_0_2_0_" class="arrow" onclick="toggleFolder('0_2_0_')">&#9660;</span><span id="img_0_2_0_" class="iconfopen" onclick="toggleFolder('0_2_0_')">&#160;</span><a class="el" href="dir_8c2d54daae461503333d1cbd1fcf808f.php" target="_self">File</a></td><td class="desc"></td></tr>
<tr id="row_0_2_0_0_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___file_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___file_8hpp.php" target="_self">NRE_File.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_i_o.php" title="IO&#39;s API. ">IO</a>'s API's Object : File </td></tr>
<tr id="row_0_2_1_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_0_2_1_" class="arrow" onclick="toggleFolder('0_2_1_')">&#9660;</span><span id="img_0_2_1_" class="iconfopen" onclick="toggleFolder('0_2_1_')">&#160;</span><a class="el" href="dir_0ca3aa3018c3eba24bd0177e1bd7d738.php" target="_self">FileStream</a></td><td class="desc"></td></tr>
<tr id="row_0_2_1_0_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_0_2_1_0_" class="arrow" onclick="toggleFolder('0_2_1_0_')">&#9660;</span><span id="img_0_2_1_0_" class="iconfopen" onclick="toggleFolder('0_2_1_0_')">&#160;</span><a class="el" href="dir_69f5a99671e0b76b37f21d1b0cdae228.php" target="_self">BinaryInput</a></td><td class="desc"></td></tr>
<tr id="row_0_2_1_0_0_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span id="arr_0_2_1_0_0_" class="arrow" onclick="toggleFolder('0_2_1_0_0_')">&#9660;</span><span id="img_0_2_1_0_0_" class="iconfopen" onclick="toggleFolder('0_2_1_0_0_')">&#160;</span><a class="el" href="dir_109d76ebc666e3f53ebc5b526a602762.php" target="_self">File</a></td><td class="desc"></td></tr>
<tr id="row_0_2_1_0_0_0_" class="even"><td class="entry"><span style="width:96px;display:inline-block;">&#160;</span><a href="_n_r_e___binary_input_file_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___binary_input_file_8hpp.php" target="_self">NRE_BinaryInputFile.hpp</a></td><td class="desc">Declaration of Engine's <a class="el" href="namespace_i_o.php" title="IO&#39;s API. ">IO</a>'s Object : BinaryInputFile </td></tr>
<tr id="row_0_2_1_0_1_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span id="arr_0_2_1_0_1_" class="arrow" onclick="toggleFolder('0_2_1_0_1_')">&#9660;</span><span id="img_0_2_1_0_1_" class="iconfopen" onclick="toggleFolder('0_2_1_0_1_')">&#160;</span><a class="el" href="dir_4e16841adf17f189d6e259d050c38fac.php" target="_self">Stream</a></td><td class="desc"></td></tr>
<tr id="row_0_2_1_0_1_0_" class="even"><td class="entry"><span style="width:96px;display:inline-block;">&#160;</span><a href="_n_r_e___binary_input_stream_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___binary_input_stream_8hpp.php" target="_self">NRE_BinaryInputStream.hpp</a></td><td class="desc">Declaration of Engine's <a class="el" href="namespace_i_o.php" title="IO&#39;s API. ">IO</a>'s Object : BinaryInputStream </td></tr>
<tr id="row_0_2_1_1_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_0_2_1_1_" class="arrow" onclick="toggleFolder('0_2_1_1_')">&#9660;</span><span id="img_0_2_1_1_" class="iconfopen" onclick="toggleFolder('0_2_1_1_')">&#160;</span><a class="el" href="dir_5d0fa741285b5fa5a304d170006408af.php" target="_self">BinaryIOFile</a></td><td class="desc"></td></tr>
<tr id="row_0_2_1_1_0_" class="even"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><a href="_n_r_e___binary_i_o_file_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___binary_i_o_file_8hpp.php" target="_self">NRE_BinaryIOFile.hpp</a></td><td class="desc">Declaratbinary ion of Engine's <a class="el" href="namespace_i_o.php" title="IO&#39;s API. ">IO</a>'s Object : BinaryIOFile </td></tr>
<tr id="row_0_2_1_2_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_0_2_1_2_" class="arrow" onclick="toggleFolder('0_2_1_2_')">&#9660;</span><span id="img_0_2_1_2_" class="iconfopen" onclick="toggleFolder('0_2_1_2_')">&#160;</span><a class="el" href="dir_ad66b28deadb5904280584043f4e9ed0.php" target="_self">BinaryOutput</a></td><td class="desc"></td></tr>
<tr id="row_0_2_1_2_0_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span id="arr_0_2_1_2_0_" class="arrow" onclick="toggleFolder('0_2_1_2_0_')">&#9660;</span><span id="img_0_2_1_2_0_" class="iconfopen" onclick="toggleFolder('0_2_1_2_0_')">&#160;</span><a class="el" href="dir_5ef021d17c5c85d9bc2db94ee9874dbb.php" target="_self">File</a></td><td class="desc"></td></tr>
<tr id="row_0_2_1_2_0_0_"><td class="entry"><span style="width:96px;display:inline-block;">&#160;</span><a href="_n_r_e___binary_output_file_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___binary_output_file_8hpp.php" target="_self">NRE_BinaryOutputFile.hpp</a></td><td class="desc">Declaration of Engine's <a class="el" href="namespace_i_o.php" title="IO&#39;s API. ">IO</a>'s Object : BinaryOutputFile </td></tr>
<tr id="row_0_2_1_2_1_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span id="arr_0_2_1_2_1_" class="arrow" onclick="toggleFolder('0_2_1_2_1_')">&#9660;</span><span id="img_0_2_1_2_1_" class="iconfopen" onclick="toggleFolder('0_2_1_2_1_')">&#160;</span><a class="el" href="dir_252c454fb8dfdd837e1efbf661b44bb8.php" target="_self">Stream</a></td><td class="desc"></td></tr>
<tr id="row_0_2_1_2_1_0_"><td class="entry"><span style="width:96px;display:inline-block;">&#160;</span><a href="_n_r_e___binary_output_stream_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___binary_output_stream_8hpp.php" target="_self">NRE_BinaryOutputStream.hpp</a></td><td class="desc">Declaration of Engine's <a class="el" href="namespace_i_o.php" title="IO&#39;s API. ">IO</a>'s Object : BinaryOutputStream </td></tr>
<tr id="row_0_2_1_3_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_0_2_1_3_" class="arrow" onclick="toggleFolder('0_2_1_3_')">&#9660;</span><span id="img_0_2_1_3_" class="iconfopen" onclick="toggleFolder('0_2_1_3_')">&#160;</span><a class="el" href="dir_9053ba190c8c29c50b61e1de2414617c.php" target="_self">Input</a></td><td class="desc"></td></tr>
<tr id="row_0_2_1_3_0_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span id="arr_0_2_1_3_0_" class="arrow" onclick="toggleFolder('0_2_1_3_0_')">&#9660;</span><span id="img_0_2_1_3_0_" class="iconfopen" onclick="toggleFolder('0_2_1_3_0_')">&#160;</span><a class="el" href="dir_8181a9acf99508f2b1bb7212ffc469b6.php" target="_self">File</a></td><td class="desc"></td></tr>
<tr id="row_0_2_1_3_0_0_" class="even"><td class="entry"><span style="width:96px;display:inline-block;">&#160;</span><a href="_n_r_e___input_file_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___input_file_8hpp.php" target="_self">NRE_InputFile.hpp</a></td><td class="desc">Declaration of Engine's <a class="el" href="namespace_i_o.php" title="IO&#39;s API. ">IO</a>'s Object : InputFile </td></tr>
<tr id="row_0_2_1_3_1_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span id="arr_0_2_1_3_1_" class="arrow" onclick="toggleFolder('0_2_1_3_1_')">&#9660;</span><span id="img_0_2_1_3_1_" class="iconfopen" onclick="toggleFolder('0_2_1_3_1_')">&#160;</span><a class="el" href="dir_385fadae8ebd31bd7c950e4a430d7d42.php" target="_self">Stream</a></td><td class="desc"></td></tr>
<tr id="row_0_2_1_3_1_0_" class="even"><td class="entry"><span style="width:96px;display:inline-block;">&#160;</span><a href="_n_r_e___input_stream_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___input_stream_8hpp.php" target="_self">NRE_InputStream.hpp</a></td><td class="desc">Declaration of Engine's <a class="el" href="namespace_i_o.php" title="IO&#39;s API. ">IO</a>'s Object : InputStream </td></tr>
<tr id="row_0_2_1_4_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_0_2_1_4_" class="arrow" onclick="toggleFolder('0_2_1_4_')">&#9660;</span><span id="img_0_2_1_4_" class="iconfopen" onclick="toggleFolder('0_2_1_4_')">&#160;</span><a class="el" href="dir_6070bc021ba14041c45485ddf2edc6d5.php" target="_self">IOFile</a></td><td class="desc"></td></tr>
<tr id="row_0_2_1_4_0_" class="even"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><a href="_n_r_e___i_o_file_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___i_o_file_8hpp.php" target="_self">NRE_IOFile.hpp</a></td><td class="desc">Declaration of Engine's <a class="el" href="namespace_i_o.php" title="IO&#39;s API. ">IO</a>'s Object : IOFile </td></tr>
<tr id="row_0_2_1_5_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_0_2_1_5_" class="arrow" onclick="toggleFolder('0_2_1_5_')">&#9660;</span><span id="img_0_2_1_5_" class="iconfopen" onclick="toggleFolder('0_2_1_5_')">&#160;</span><a class="el" href="dir_e5f6d8b1531c0dcd5388e93cbfd72a55.php" target="_self">Output</a></td><td class="desc"></td></tr>
<tr id="row_0_2_1_5_0_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span id="arr_0_2_1_5_0_" class="arrow" onclick="toggleFolder('0_2_1_5_0_')">&#9660;</span><span id="img_0_2_1_5_0_" class="iconfopen" onclick="toggleFolder('0_2_1_5_0_')">&#160;</span><a class="el" href="dir_296f90fc55d16f5d18e74ae2db15dc5e.php" target="_self">File</a></td><td class="desc"></td></tr>
<tr id="row_0_2_1_5_0_0_"><td class="entry"><span style="width:96px;display:inline-block;">&#160;</span><a href="_n_r_e___output_file_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___output_file_8hpp.php" target="_self">NRE_OutputFile.hpp</a></td><td class="desc">Declaration of Engine's <a class="el" href="namespace_i_o.php" title="IO&#39;s API. ">IO</a>'s Object : OutputFile </td></tr>
<tr id="row_0_2_1_5_1_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span id="arr_0_2_1_5_1_" class="arrow" onclick="toggleFolder('0_2_1_5_1_')">&#9660;</span><span id="img_0_2_1_5_1_" class="iconfopen" onclick="toggleFolder('0_2_1_5_1_')">&#160;</span><a class="el" href="dir_05a885a8e57ea792255b94a13f14e89d.php" target="_self">Stream</a></td><td class="desc"></td></tr>
<tr id="row_0_2_1_5_1_0_"><td class="entry"><span style="width:96px;display:inline-block;">&#160;</span><a href="_n_r_e___output_stream_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___output_stream_8hpp.php" target="_self">NRE_OutputStream.hpp</a></td><td class="desc">Declaration of Engine's <a class="el" href="namespace_i_o.php" title="IO&#39;s API. ">IO</a>'s Object : OutputStream </td></tr>
<tr id="row_0_2_1_6_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___file_stream_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___file_stream_8hpp.php" target="_self">NRE_FileStream.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_i_o.php" title="IO&#39;s API. ">IO</a>'s API's Object : FileStream </td></tr>
<tr id="row_0_3_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icondoc"></span><a class="el" href="_n_r_e___main_8cpp.php" target="_self">NRE_Main.cpp</a></td><td class="desc">Test of <a class="el" href="namespace_i_o.php" title="IO&#39;s API. ">IO</a>'s API </td></tr>
</table>
</div><!-- directory -->
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
