<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-IO: Class Members</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li class="current"><a href="functions.php"><span>All</span></a></li>
      <li><a href="functions_func.php"><span>Functions</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="#index_b"><span>b</span></a></li>
      <li><a href="#index_e"><span>e</span></a></li>
      <li><a href="#index_f"><span>f</span></a></li>
      <li><a href="#index_g"><span>g</span></a></li>
      <li><a href="#index_i"><span>i</span></a></li>
      <li><a href="#index_o"><span>o</span></a></li>
      <li><a href="#index_r"><span>r</span></a></li>
      <li><a href="#index_s"><span>s</span></a></li>
      <li><a href="#index_t"><span>t</span></a></li>
      <li><a href="#index_w"><span>w</span></a></li>
      <li class="current"><a href="#index_0x7e"><span>~</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
<div class="textblock">Here is a list of all documented class members with links to the class documentation for each member:</div>

<h3><a class="anchor" id="index_b"></a>- b -</h3><ul>
<li>BinaryInputFile()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_file.php#a2c6b1d8d43e4c609f1fcead085f8d1b3">NRE::IO::BinaryInputFile</a>
</li>
<li>BinaryInputStream()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#a63da2d140ad77e663a65076df5cdb944">NRE::IO::BinaryInputStream</a>
</li>
<li>BinaryIOFile()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_i_o_file.php#a264ea8e81b656b645b53097882216995">NRE::IO::BinaryIOFile</a>
</li>
<li>BinaryOutputFile()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php#a96cc5fe5e9c01f1460ed8ffe96f7c719">NRE::IO::BinaryOutputFile</a>
</li>
<li>BinaryOutputStream()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php#af82285fba8d579c92c13a6ab8c6ea1f8">NRE::IO::BinaryOutputStream</a>
</li>
</ul>


<h3><a class="anchor" id="index_e"></a>- e -</h3><ul>
<li>exist()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#ae955f8bc07d667649e7f045c2bbbef49">NRE::IO::File</a>
</li>
</ul>


<h3><a class="anchor" id="index_f"></a>- f -</h3><ul>
<li>File()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#ae31e8c433fdbda9a37130168b5fb2858">NRE::IO::File</a>
</li>
<li>FileNotExistingException()
: <a class="el" href="class_n_r_e_1_1_exception_1_1_file_not_existing_exception.php#a17e35346a2e00d483117581ec71cbc9f">NRE::Exception::FileNotExistingException</a>
</li>
<li>FileNotOpeningException()
: <a class="el" href="class_n_r_e_1_1_exception_1_1_file_not_opening_exception.php#ae5762928257e5523f159f98f10aad64f">NRE::Exception::FileNotOpeningException</a>
</li>
<li>FileStream()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#afc239902cef34ecfd890cf69a5172c6d">NRE::IO::FileStream</a>
</li>
</ul>


<h3><a class="anchor" id="index_g"></a>- g -</h3><ul>
<li>getMode()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_file.php#a263d8103d171e7cc001c8e1c9ec3b6f2">NRE::IO::BinaryInputFile</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_i_o_file.php#a6006dcdd0149b41dfc935b0eb2132237">NRE::IO::BinaryIOFile</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php#aab5124d17d117c920d5f8ffe48e0226a">NRE::IO::BinaryOutputFile</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#abfef164a828872b9e1eb7d7e01344c1b">NRE::IO::FileStream</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php#a4c8886a207655e70e21f23f1a694e3dd">NRE::IO::InputFile</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_i_o_file.php#a88546f6403e21b1b0cfafe956033c32f">NRE::IO::IOFile</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_output_file.php#a8878a1a46a6487059844d6dcf495c3a3">NRE::IO::OutputFile</a>
</li>
<li>getPath()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a6ff1d432623961e08ed64eeb97d547c7">NRE::IO::File</a>
</li>
<li>getPosition()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#abbf6f1014d1be839a1841c51bad87b3c">NRE::IO::InputStream</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a4865057a0271a36ec3cde6e76282ebfc">NRE::IO::OutputStream</a>
</li>
<li>getStream()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_file.php#abd74b00ec06cb5c1c828a68024af2f2a">NRE::IO::BinaryInputFile</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#a746061ba00a5188ddf5d55143c7aed4b">NRE::IO::BinaryInputStream</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_i_o_file.php#ae312212af94dc55296cbeec60806b2bc">NRE::IO::BinaryIOFile</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php#a226f850a5fc4d714d97c5688e94c1d7e">NRE::IO::BinaryOutputFile</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php#afc14dff50cead68bef5210966d3e5f58">NRE::IO::BinaryOutputStream</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#a36c7a3ca5e4e79e6f706577d04d3bffe">NRE::IO::FileStream</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php#a8a06ca02590f62804bcaa2fd08c54538">NRE::IO::InputFile</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#a4e61262f16391d9a592093cc13ed85d8">NRE::IO::InputStream</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_i_o_file.php#a0f6ed5ca0893d4444e439ac07e391e67">NRE::IO::IOFile</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_output_file.php#a009140e861b7b27f2a1569a833081303">NRE::IO::OutputFile</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#aa67ea34d4faa3bbd24d9df13979be205">NRE::IO::OutputStream</a>
</li>
</ul>


<h3><a class="anchor" id="index_i"></a>- i -</h3><ul>
<li>InputFile()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php#a692608a4559e9eb9ff281e5b88ef6cab">NRE::IO::InputFile</a>
</li>
<li>InputStream()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#ae77d706d7e3c1a59353d88b0e1ff9476">NRE::IO::InputStream</a>
</li>
<li>IOException()
: <a class="el" href="class_n_r_e_1_1_exception_1_1_i_o_exception.php#a855a98a399ad4bbc1f1be2ad2da1cf24">NRE::Exception::IOException</a>
</li>
<li>IOFile()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_i_o_file.php#ac9defd8f4c2c0728523534ebee53af7c">NRE::IO::IOFile</a>
</li>
<li>isOpen()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#a6cb9f46d893839b4518cc86b3afe2178">NRE::IO::FileStream</a>
</li>
</ul>


<h3><a class="anchor" id="index_o"></a>- o -</h3><ul>
<li>open()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#a24979d0affac7992e181820b881941eb">NRE::IO::FileStream</a>
</li>
<li>openEmpty()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#af0677c0d90634a88472f629567ca5238">NRE::IO::FileStream</a>
</li>
<li>operator+()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a2009e071a45be3a88bcfc03bd7868b50">NRE::IO::File</a>
</li>
<li>operator=()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_file.php#a354012cd7a8fff209c716d1d96899394">NRE::IO::BinaryInputFile</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#aa72a8c1f1905ca197325afbcba4cd7ed">NRE::IO::BinaryInputStream</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_i_o_file.php#a4975ecca44300ab970706f06b3e04019">NRE::IO::BinaryIOFile</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php#a0e11dce33943c88dbcce066995fb67e2">NRE::IO::BinaryOutputFile</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php#a29955b656accd131c03a1e3e2c7f352c">NRE::IO::BinaryOutputStream</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a94972246304fc4df0e029d0f657b86ae">NRE::IO::File</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#a357c757b87bc7876f0b1f2fb7f96edb1">NRE::IO::FileStream</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php#a0e874eb62d5ee7e5e2ef1787422c81b6">NRE::IO::InputFile</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#ae268a182a6e21b17ccb8f6e2af98d2b2">NRE::IO::InputStream</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_i_o_file.php#acf5050ff0b1b338fb68749672cc2aec2">NRE::IO::IOFile</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_output_file.php#a05d4699bd6aaca11eedc5e398a2ba4f6">NRE::IO::OutputFile</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a19aca25943b90833a09c633f2ad4a097">NRE::IO::OutputStream</a>
</li>
<li>OutputFile()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_output_file.php#acefaded29c0882612f591c31b906ec79">NRE::IO::OutputFile</a>
</li>
<li>OutputStream()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a7113e072849339312d22fb688dd18476">NRE::IO::OutputStream</a>
</li>
</ul>


<h3><a class="anchor" id="index_r"></a>- r -</h3><ul>
<li>read()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#a4863ac832c227dc838e4d8a74db97c6a">NRE::IO::InputStream</a>
</li>
<li>readBinary()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#acec53ec7e9fa9adb1b7ad8b50f7364c8">NRE::IO::BinaryInputStream</a>
</li>
<li>readLine()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#af91eeb1fc3eb2a8ea3c623d0d140e6a4">NRE::IO::InputStream</a>
</li>
</ul>


<h3><a class="anchor" id="index_s"></a>- s -</h3><ul>
<li>seekBegin()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#a7365375159cb13f7d4d1004e39a622c3">NRE::IO::InputStream</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#ab17afff8528ac5d7ba2fd8a5577022e2">NRE::IO::OutputStream</a>
</li>
<li>seekEnd()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#ae0fbdbcce3b727547ad94f035608906d">NRE::IO::InputStream</a>
, <a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a78c55f5724508b1cd92aea071306029d">NRE::IO::OutputStream</a>
</li>
<li>setPath()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a1414f962cf4bcae9450b66643f8e3d67">NRE::IO::File</a>
</li>
</ul>


<h3><a class="anchor" id="index_t"></a>- t -</h3><ul>
<li>toString()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a0137a4cc6e43c091bc88e485eb29b91f">NRE::IO::File</a>
</li>
</ul>


<h3><a class="anchor" id="index_w"></a>- w -</h3><ul>
<li>write()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#a2347d2de8cf213aee37148c25c5bdf6c">NRE::IO::OutputStream</a>
</li>
<li>writeBinary()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php#a82c8c1174443122100e617f153989071">NRE::IO::BinaryOutputStream</a>
</li>
</ul>


<h3><a class="anchor" id="index_0x7e"></a>- ~ -</h3><ul>
<li>~BinaryInputFile()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_file.php#aa97245557166406d48555b6734b30a2f">NRE::IO::BinaryInputFile</a>
</li>
<li>~BinaryInputStream()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php#ac39b3d01a85995cebacdfa64a1a1b588">NRE::IO::BinaryInputStream</a>
</li>
<li>~BinaryIOFile()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_i_o_file.php#a9c742c524402c6701c50bdc738994071">NRE::IO::BinaryIOFile</a>
</li>
<li>~BinaryOutputFile()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php#a799573c27d504e89bd7512a57caee395">NRE::IO::BinaryOutputFile</a>
</li>
<li>~BinaryOutputStream()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php#aa3465fcc7636a59bbe506b55a2c749b4">NRE::IO::BinaryOutputStream</a>
</li>
<li>~File()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php#a915cdede01e62ea1c8a0a970480a53af">NRE::IO::File</a>
</li>
<li>~FileStream()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php#a85b97b37c6487fa16924773adcc90d12">NRE::IO::FileStream</a>
</li>
<li>~InputFile()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php#a01cc8f3e1193bfa3167c5b7d7f85a9d6">NRE::IO::InputFile</a>
</li>
<li>~InputStream()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php#a6640a5cd0ec7f081452aea53bde44f34">NRE::IO::InputStream</a>
</li>
<li>~IOFile()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_i_o_file.php#a95225a72ce8036c8dbd771db7f14438e">NRE::IO::IOFile</a>
</li>
<li>~OutputFile()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_output_file.php#a247e5ee5620e365af61372f0bea51eda">NRE::IO::OutputFile</a>
</li>
<li>~OutputStream()
: <a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php#ab93399476f8933a7062c9ab3c0db0e05">NRE::IO::OutputStream</a>
</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
