<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-IO: Class Hierarchy</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li class="current"><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Class Hierarchy</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock">This inheritance list is sorted roughly, but not completely, alphabetically:</div><div class="directory">
<div class="levels">[detail level <span onclick="javascript:toggleLevel(1);">1</span><span onclick="javascript:toggleLevel(2);">2</span><span onclick="javascript:toggleLevel(3);">3</span><span onclick="javascript:toggleLevel(4);">4</span>]</div><table class="directory">
<tr id="row_0_" class="even"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_0_" class="arrow" onclick="toggleFolder('0_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_stream.php" target="_self">NRE::IO::BinaryInputStream</a></td><td class="desc">Base interface for binary input related stream </td></tr>
<tr id="row_0_0_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_file.php" target="_self">NRE::IO::BinaryInputFile</a></td><td class="desc">Manage binary input file stream </td></tr>
<tr id="row_0_1_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_i_o_file.php" target="_self">NRE::IO::BinaryIOFile</a></td><td class="desc">Manage Binary Input-Output file stream </td></tr>
<tr id="row_1_"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_1_" class="arrow" onclick="toggleFolder('1_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_stream.php" target="_self">NRE::IO::BinaryOutputStream</a></td><td class="desc">Base interface for binary output related stream </td></tr>
<tr id="row_1_0_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_i_o_file.php" target="_self">NRE::IO::BinaryIOFile</a></td><td class="desc">Manage Binary Input-Output file stream </td></tr>
<tr id="row_1_1_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php" target="_self">NRE::IO::BinaryOutputFile</a></td><td class="desc">Manage binary output file stream </td></tr>
<tr id="row_2_" class="even"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_2_" class="arrow" onclick="toggleFolder('2_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_i_o_1_1_file.php" target="_self">NRE::IO::File</a></td><td class="desc">Manage a file path and ensure that's the file exist before accessing it </td></tr>
<tr id="row_2_0_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_2_0_" class="arrow" onclick="toggleFolder('2_0_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_i_o_1_1_file_stream.php" target="_self">NRE::IO::FileStream</a></td><td class="desc">The base interface for Input, Output and <a class="el" href="namespace_i_o.php" title="IO&#39;s API. ">IO</a> file </td></tr>
<tr id="row_2_0_0_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_2_0_0_" class="arrow" onclick="toggleFolder('2_0_0_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php" target="_self">NRE::IO::InputFile</a></td><td class="desc">Manage input file stream </td></tr>
<tr id="row_2_0_0_0_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_input_file.php" target="_self">NRE::IO::BinaryInputFile</a></td><td class="desc">Manage binary input file stream </td></tr>
<tr id="row_2_0_1_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_2_0_1_" class="arrow" onclick="toggleFolder('2_0_1_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_i_o_1_1_i_o_file.php" target="_self">NRE::IO::IOFile</a></td><td class="desc">Manage Input-Output file stream </td></tr>
<tr id="row_2_0_1_0_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_i_o_file.php" target="_self">NRE::IO::BinaryIOFile</a></td><td class="desc">Manage Binary Input-Output file stream </td></tr>
<tr id="row_2_0_2_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_2_0_2_" class="arrow" onclick="toggleFolder('2_0_2_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_file.php" target="_self">NRE::IO::OutputFile</a></td><td class="desc">Manage output file stream </td></tr>
<tr id="row_2_0_2_0_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_i_o_1_1_binary_output_file.php" target="_self">NRE::IO::BinaryOutputFile</a></td><td class="desc">Manage binary output file stream </td></tr>
<tr id="row_3_" class="even"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_3_" class="arrow" onclick="toggleFolder('3_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><b>IException</b></td><td class="desc"></td></tr>
<tr id="row_3_0_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_3_0_" class="arrow" onclick="toggleFolder('3_0_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_exception_1_1_i_o_exception.php" target="_self">NRE::Exception::IOException</a></td><td class="desc">An exception thrown by io operation </td></tr>
<tr id="row_3_0_0_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_exception_1_1_file_not_existing_exception.php" target="_self">NRE::Exception::FileNotExistingException</a></td><td class="desc">An exception thrown when attempting an operation on a unexisting file </td></tr>
<tr id="row_3_0_1_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_exception_1_1_file_not_opening_exception.php" target="_self">NRE::Exception::FileNotOpeningException</a></td><td class="desc">An exception thrown when attempting to open a file </td></tr>
<tr id="row_4_" class="even"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_4_" class="arrow" onclick="toggleFolder('4_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_stream.php" target="_self">NRE::IO::InputStream</a></td><td class="desc">Base interface for input related stream </td></tr>
<tr id="row_4_0_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_i_o_1_1_input_file.php" target="_self">NRE::IO::InputFile</a></td><td class="desc">Manage input file stream </td></tr>
<tr id="row_4_1_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_i_o_1_1_i_o_file.php" target="_self">NRE::IO::IOFile</a></td><td class="desc">Manage Input-Output file stream </td></tr>
<tr id="row_5_"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_5_" class="arrow" onclick="toggleFolder('5_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_stream.php" target="_self">NRE::IO::OutputStream</a></td><td class="desc">Base interface for output related stream </td></tr>
<tr id="row_5_0_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_i_o_1_1_i_o_file.php" target="_self">NRE::IO::IOFile</a></td><td class="desc">Manage Input-Output file stream </td></tr>
<tr id="row_5_1_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_i_o_1_1_output_file.php" target="_self">NRE::IO::OutputFile</a></td><td class="desc">Manage output file stream </td></tr>
</table>
</div><!-- directory -->
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
